// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidApplicationMessage.proto

package com.stupidbeauty.hxlauncher;

public interface AndroidApplicationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.AndroidApplicationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *包名字。
   * </pre>
   *
   * <code>string packageName = 1;</code>
   * @return The packageName.
   */
  java.lang.String getPackageName();
  /**
   * <pre>
   *包名字。
   * </pre>
   *
   * <code>string packageName = 1;</code>
   * @return The bytes for packageName.
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();

  /**
   * <pre>
   *活动名字。
   * </pre>
   *
   * <code>string activityName = 2;</code>
   * @return The activityName.
   */
  java.lang.String getActivityName();
  /**
   * <pre>
   *活动名字。
   * </pre>
   *
   * <code>string activityName = 2;</code>
   * @return The bytes for activityName.
   */
  com.google.protobuf.ByteString
      getActivityNameBytes();

  /**
   * <pre>
   *!&lt;快捷方式编号．
   * </pre>
   *
   * <code>string shortcutId = 3;</code>
   * @return The shortcutId.
   */
  java.lang.String getShortcutId();
  /**
   * <pre>
   *!&lt;快捷方式编号．
   * </pre>
   *
   * <code>string shortcutId = 3;</code>
   * @return The bytes for shortcutId.
   */
  com.google.protobuf.ByteString
      getShortcutIdBytes();

  /**
   * <pre>
   *!&lt;图标类型．
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 4;</code>
   * @return The enum numeric value on the wire for iconType.
   */
  int getIconTypeValue();
  /**
   * <pre>
   *!&lt;图标类型．
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 4;</code>
   * @return The iconType.
   */
  com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType();

  /**
   * <pre>
   *!&lt;安装包的下载地址。
   * </pre>
   *
   * <code>string packageUrl = 5;</code>
   * @return The packageUrl.
   */
  java.lang.String getPackageUrl();
  /**
   * <pre>
   *!&lt;安装包的下载地址。
   * </pre>
   *
   * <code>string packageUrl = 5;</code>
   * @return The bytes for packageUrl.
   */
  com.google.protobuf.ByteString
      getPackageUrlBytes();
}
