// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidApplicationMessage.proto

package com.stupidbeauty.hxlauncher;

public final class AndroidApplicationMessageProtos {
  private AndroidApplicationMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037AndroidApplicationMessage.proto\022\033com.s" +
      "tupidbeauty.hxlauncher\032\030HxLauncherIconTy" +
      "pe.proto\"\261\001\n\031AndroidApplicationMessage\022\023" +
      "\n\013packageName\030\001 \001(\t\022\024\n\014activityName\030\002 \001(" +
      "\t\022\022\n\nshortcutId\030\003 \001(\t\022A\n\010iconType\030\004 \001(\0162" +
      "/.com.stupidbeauty.hxlauncher.HxLauncher" +
      "IconType\022\022\n\npackageUrl\030\005 \001(\tB@\n\033com.stup" +
      "idbeauty.hxlauncherB\037AndroidApplicationM" +
      "essageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_descriptor,
        new java.lang.String[] { "PackageName", "ActivityName", "ShortcutId", "IconType", "PackageUrl", });
    com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
