// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidApplicationsListMessage.proto

package com.stupidbeauty.hxlauncher;

public final class AndroidApplicationsListMessageProtos {
  private AndroidApplicationsListMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationsListMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationsListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$AndroidApplicationsListMessage.proto\022\033" +
      "com.stupidbeauty.hxlauncher\032\037ReportAudio" +
      "SoundSourceReq.proto\032*Set3DEngineCameraP" +
      "ositionRotationReq.proto\032\034CameraSubSyste" +
      "mMessage.proto\032\037AndroidApplicationMessag" +
      "e.proto\"\241\003\n\036AndroidApplicationsListMessa" +
      "ge\022S\n\023androidApplications\030\001 \003(\01326.com.st" +
      "upidbeauty.hxlauncher.AndroidApplication" +
      "Message\022S\n\026cameraSubSystemMessage\030\002 \001(\0132" +
      "3.com.stupidbeauty.hxlauncher.CameraSubS" +
      "ystemMessage\022`\n reportAudioSoundSourceRe" +
      "qMessage\030\006 \001(\01326.com.stupidbeauty.hxlaun" +
      "cher.ReportAudioSoundSourceReq\022s\n(set3DE" +
      "ngineCameraPositionRotationMessage\030\010 \001(\013" +
      "2A.com.stupidbeauty.hxlauncher.Set3DEngi" +
      "neCameraPositionRotationReqBE\n\033com.stupi" +
      "dbeauty.hxlauncherB$AndroidApplicationsL" +
      "istMessageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.CameraSubSystemMessageProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationsListMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationsListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationsListMessage_descriptor,
        new java.lang.String[] { "AndroidApplications", "CameraSubSystemMessage", "ReportAudioSoundSourceReqMessage", "Set3DEngineCameraPositionRotationMessage", });
    com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.CameraSubSystemMessageProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
