// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidApplicationsListMessage.proto

package com.stupidbeauty.hxlauncher;

public interface AndroidApplicationsListMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.AndroidApplicationsListMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *安卓应用列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage androidApplications = 1;</code>
   */
  java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage> 
      getAndroidApplicationsList();
  /**
   * <pre>
   *安卓应用列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage androidApplications = 1;</code>
   */
  com.stupidbeauty.hxlauncher.AndroidApplicationMessage getAndroidApplications(int index);
  /**
   * <pre>
   *安卓应用列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage androidApplications = 1;</code>
   */
  int getAndroidApplicationsCount();
  /**
   * <pre>
   *安卓应用列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage androidApplications = 1;</code>
   */
  java.util.List<? extends com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder> 
      getAndroidApplicationsOrBuilderList();
  /**
   * <pre>
   *安卓应用列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage androidApplications = 1;</code>
   */
  com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder getAndroidApplicationsOrBuilder(
      int index);

  /**
   * <pre>
   *摄像头子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.CameraSubSystemMessage cameraSubSystemMessage = 2;</code>
   * @return Whether the cameraSubSystemMessage field is set.
   */
  boolean hasCameraSubSystemMessage();
  /**
   * <pre>
   *摄像头子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.CameraSubSystemMessage cameraSubSystemMessage = 2;</code>
   * @return The cameraSubSystemMessage.
   */
  com.stupidbeauty.hxlauncher.CameraSubSystemMessage getCameraSubSystemMessage();
  /**
   * <pre>
   *摄像头子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.CameraSubSystemMessage cameraSubSystemMessage = 2;</code>
   */
  com.stupidbeauty.hxlauncher.CameraSubSystemMessageOrBuilder getCameraSubSystemMessageOrBuilder();

  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return Whether the reportAudioSoundSourceReqMessage field is set.
   */
  boolean hasReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return The reportAudioSoundSourceReqMessage.
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder();

  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   * @return Whether the set3DEngineCameraPositionRotationMessage field is set.
   */
  boolean hasSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   * @return The set3DEngineCameraPositionRotationMessage.
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq getSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder getSet3DEngineCameraPositionRotationMessageOrBuilder();
}
