// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public interface CameraSubSystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.CameraSubSystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *主控系统的IP。
   * </pre>
   *
   * <code>string logicControlIp = 1;</code>
   * @return The logicControlIp.
   */
  java.lang.String getLogicControlIp();
  /**
   * <pre>
   *主控系统的IP。
   * </pre>
   *
   * <code>string logicControlIp = 1;</code>
   * @return The bytes for logicControlIp.
   */
  com.google.protobuf.ByteString
      getLogicControlIpBytes();

  /**
   * <pre>
   *摄像头编号。
   * </pre>
   *
   * <code>int32 cameraId = 2;</code>
   * @return The cameraId.
   */
  int getCameraId();

  /**
   * <pre>
   *人脸检测频率。
   * </pre>
   *
   * <code>float faceDetectFrequency = 3;</code>
   * @return The faceDetectFrequency.
   */
  float getFaceDetectFrequency();

  /**
   * <pre>
   *人脸检测模式。
   * </pre>
   *
   * <code>string faceDetectMode = 4;</code>
   * @return The faceDetectMode.
   */
  java.lang.String getFaceDetectMode();
  /**
   * <pre>
   *人脸检测模式。
   * </pre>
   *
   * <code>string faceDetectMode = 4;</code>
   * @return The bytes for faceDetectMode.
   */
  com.google.protobuf.ByteString
      getFaceDetectModeBytes();

  /**
   * <pre>
   *是否要自动开始进行人脸检测。
   * </pre>
   *
   * <code>bool autoStartFaceDetect = 5;</code>
   * @return The autoStartFaceDetect.
   */
  boolean getAutoStartFaceDetect();

  /**
   * <pre>
   *服务器端人脸检测服务的网址。
   * </pre>
   *
   * <code>string ibotexServerFaceDetectUrl = 6;</code>
   * @return The ibotexServerFaceDetectUrl.
   */
  java.lang.String getIbotexServerFaceDetectUrl();
  /**
   * <pre>
   *服务器端人脸检测服务的网址。
   * </pre>
   *
   * <code>string ibotexServerFaceDetectUrl = 6;</code>
   * @return The bytes for ibotexServerFaceDetectUrl.
   */
  com.google.protobuf.ByteString
      getIbotexServerFaceDetectUrlBytes();

  /**
   * <pre>
   *服务器端人脸识别服务的网址。
   * </pre>
   *
   * <code>string ibotexServerFaceRecognizeUrl = 7;</code>
   * @return The ibotexServerFaceRecognizeUrl.
   */
  java.lang.String getIbotexServerFaceRecognizeUrl();
  /**
   * <pre>
   *服务器端人脸识别服务的网址。
   * </pre>
   *
   * <code>string ibotexServerFaceRecognizeUrl = 7;</code>
   * @return The bytes for ibotexServerFaceRecognizeUrl.
   */
  com.google.protobuf.ByteString
      getIbotexServerFaceRecognizeUrlBytes();

  /**
   * <pre>
   *二维码扫描和嘉宾证识别混合接口的网址。
   * </pre>
   *
   * <code>string extQrOcrHybridServiceUrl = 8;</code>
   * @return The extQrOcrHybridServiceUrl.
   */
  java.lang.String getExtQrOcrHybridServiceUrl();
  /**
   * <pre>
   *二维码扫描和嘉宾证识别混合接口的网址。
   * </pre>
   *
   * <code>string extQrOcrHybridServiceUrl = 8;</code>
   * @return The bytes for extQrOcrHybridServiceUrl.
   */
  com.google.protobuf.ByteString
      getExtQrOcrHybridServiceUrlBytes();

  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return Whether the reportAccurateVoiceCommandMessage field is set.
   */
  boolean hasReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return The reportAccurateVoiceCommandMessage.
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq getReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder getReportAccurateVoiceCommandMessageOrBuilder();

  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return Whether the reportVoiceRecognizedMessage field is set.
   */
  boolean hasReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return The reportVoiceRecognizedMessage.
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder();
}
