// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CameraSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public final class CameraSubSystemMessageProtos {
  private CameraSubSystemMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_CameraSubSystemMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_CameraSubSystemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034CameraSubSystemMessage.proto\022\033com.stup" +
      "idbeauty.hxlauncher\032\035AccurateVoiceComman" +
      "dReq.proto\032\036ReportVoiceRecognizedReq.pro" +
      "to\"\275\003\n\026CameraSubSystemMessage\022\026\n\016logicCo" +
      "ntrolIp\030\001 \001(\t\022\020\n\010cameraId\030\002 \001(\005\022\033\n\023faceD" +
      "etectFrequency\030\003 \001(\002\022\026\n\016faceDetectMode\030\004" +
      " \001(\t\022\033\n\023autoStartFaceDetect\030\005 \001(\010\022!\n\031ibo" +
      "texServerFaceDetectUrl\030\006 \001(\t\022$\n\034ibotexSe" +
      "rverFaceRecognizeUrl\030\007 \001(\t\022 \n\030extQrOcrHy" +
      "bridServiceUrl\030\010 \001(\t\022_\n!reportAccurateVo" +
      "iceCommandMessage\030\023 \001(\01324.com.stupidbeau" +
      "ty.hxlauncher.AccurateVoiceCommandReq\022[\n" +
      "\034reportVoiceRecognizedMessage\030\024 \001(\01325.co" +
      "m.stupidbeauty.hxlauncher.ReportVoiceRec" +
      "ognizedReqB=\n\033com.stupidbeauty.hxlaunche" +
      "rB\034CameraSubSystemMessageProtosP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_CameraSubSystemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_CameraSubSystemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_CameraSubSystemMessage_descriptor,
        new java.lang.String[] { "LogicControlIp", "CameraId", "FaceDetectFrequency", "FaceDetectMode", "AutoStartFaceDetect", "IbotexServerFaceDetectUrl", "IbotexServerFaceRecognizeUrl", "ExtQrOcrHybridServiceUrl", "ReportAccurateVoiceCommandMessage", "ReportVoiceRecognizedMessage", });
    com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
