// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigurationMessage.proto

package com.stupidbeauty.hxlauncher;

public final class ConfigurationMessageOuterClass {
  private ConfigurationMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigurationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ConfigurationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *麦克风子系统的配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
     * @return Whether the microphoneSubSystem field is set.
     */
    boolean hasMicrophoneSubSystem();
    /**
     * <pre>
     *麦克风子系统的配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
     * @return The microphoneSubSystem.
     */
    com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage getMicrophoneSubSystem();
    /**
     * <pre>
     *麦克风子系统的配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
     */
    com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageOrBuilder getMicrophoneSubSystemOrBuilder();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.ConfigurationMessage}
   */
  public  static final class ConfigurationMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.ConfigurationMessage)
      ConfigurationMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConfigurationMessage.newBuilder() to construct.
    private ConfigurationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigurationMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConfigurationMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConfigurationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 66: {
              com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.Builder subBuilder = null;
              if (microphoneSubSystem_ != null) {
                subBuilder = microphoneSubSystem_.toBuilder();
              }
              microphoneSubSystem_ = input.readMessage(com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(microphoneSubSystem_);
                microphoneSubSystem_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.class, com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.Builder.class);
    }

    public static final int MICROPHONESUBSYSTEM_FIELD_NUMBER = 8;
    private com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem_;
    /**
     * <pre>
     *麦克风子系统的配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
     * @return Whether the microphoneSubSystem field is set.
     */
    public boolean hasMicrophoneSubSystem() {
      return microphoneSubSystem_ != null;
    }
    /**
     * <pre>
     *麦克风子系统的配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
     * @return The microphoneSubSystem.
     */
    public com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage getMicrophoneSubSystem() {
      return microphoneSubSystem_ == null ? com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.getDefaultInstance() : microphoneSubSystem_;
    }
    /**
     * <pre>
     *麦克风子系统的配置文件信息。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
     */
    public com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageOrBuilder getMicrophoneSubSystemOrBuilder() {
      return getMicrophoneSubSystem();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (microphoneSubSystem_ != null) {
        output.writeMessage(8, getMicrophoneSubSystem());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (microphoneSubSystem_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getMicrophoneSubSystem());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage other = (com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage) obj;

      if (hasMicrophoneSubSystem() != other.hasMicrophoneSubSystem()) return false;
      if (hasMicrophoneSubSystem()) {
        if (!getMicrophoneSubSystem()
            .equals(other.getMicrophoneSubSystem())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMicrophoneSubSystem()) {
        hash = (37 * hash) + MICROPHONESUBSYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getMicrophoneSubSystem().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.ConfigurationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.ConfigurationMessage)
        com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.class, com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (microphoneSubSystemBuilder_ == null) {
          microphoneSubSystem_ = null;
        } else {
          microphoneSubSystem_ = null;
          microphoneSubSystemBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage build() {
        com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage buildPartial() {
        com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage result = new com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage(this);
        if (microphoneSubSystemBuilder_ == null) {
          result.microphoneSubSystem_ = microphoneSubSystem_;
        } else {
          result.microphoneSubSystem_ = microphoneSubSystemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage) {
          return mergeFrom((com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage other) {
        if (other == com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage.getDefaultInstance()) return this;
        if (other.hasMicrophoneSubSystem()) {
          mergeMicrophoneSubSystem(other.getMicrophoneSubSystem());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage, com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.Builder, com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageOrBuilder> microphoneSubSystemBuilder_;
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       * @return Whether the microphoneSubSystem field is set.
       */
      public boolean hasMicrophoneSubSystem() {
        return microphoneSubSystemBuilder_ != null || microphoneSubSystem_ != null;
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       * @return The microphoneSubSystem.
       */
      public com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage getMicrophoneSubSystem() {
        if (microphoneSubSystemBuilder_ == null) {
          return microphoneSubSystem_ == null ? com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.getDefaultInstance() : microphoneSubSystem_;
        } else {
          return microphoneSubSystemBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      public Builder setMicrophoneSubSystem(com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage value) {
        if (microphoneSubSystemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          microphoneSubSystem_ = value;
          onChanged();
        } else {
          microphoneSubSystemBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      public Builder setMicrophoneSubSystem(
          com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.Builder builderForValue) {
        if (microphoneSubSystemBuilder_ == null) {
          microphoneSubSystem_ = builderForValue.build();
          onChanged();
        } else {
          microphoneSubSystemBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      public Builder mergeMicrophoneSubSystem(com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage value) {
        if (microphoneSubSystemBuilder_ == null) {
          if (microphoneSubSystem_ != null) {
            microphoneSubSystem_ =
              com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.newBuilder(microphoneSubSystem_).mergeFrom(value).buildPartial();
          } else {
            microphoneSubSystem_ = value;
          }
          onChanged();
        } else {
          microphoneSubSystemBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      public Builder clearMicrophoneSubSystem() {
        if (microphoneSubSystemBuilder_ == null) {
          microphoneSubSystem_ = null;
          onChanged();
        } else {
          microphoneSubSystem_ = null;
          microphoneSubSystemBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      public com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.Builder getMicrophoneSubSystemBuilder() {
        
        onChanged();
        return getMicrophoneSubSystemFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      public com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageOrBuilder getMicrophoneSubSystemOrBuilder() {
        if (microphoneSubSystemBuilder_ != null) {
          return microphoneSubSystemBuilder_.getMessageOrBuilder();
        } else {
          return microphoneSubSystem_ == null ?
              com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.getDefaultInstance() : microphoneSubSystem_;
        }
      }
      /**
       * <pre>
       *麦克风子系统的配置文件信息。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage microphoneSubSystem = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage, com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.Builder, com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageOrBuilder> 
          getMicrophoneSubSystemFieldBuilder() {
        if (microphoneSubSystemBuilder_ == null) {
          microphoneSubSystemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage, com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage.Builder, com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageOrBuilder>(
                  getMicrophoneSubSystem(),
                  getParentForChildren(),
                  isClean());
          microphoneSubSystem_ = null;
        }
        return microphoneSubSystemBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.ConfigurationMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.ConfigurationMessage)
    private static final com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage();
    }

    public static com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigurationMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConfigurationMessage>() {
      @java.lang.Override
      public ConfigurationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConfigurationMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigurationMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigurationMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ConfigurationMessageOuterClass.ConfigurationMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ConfigurationMessage.proto\022\033com.stupid" +
      "beauty.hxlauncher\032 MicrophoneSubSystemMe" +
      "ssage.proto\"l\n\024ConfigurationMessage\022T\n\023m" +
      "icrophoneSubSystem\030\010 \001(\01327.com.stupidbea" +
      "uty.hxlauncher.MicrophoneSubSystemMessag" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ConfigurationMessage_descriptor,
        new java.lang.String[] { "MicrophoneSubSystem", });
    com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
