// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisplaySubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public interface DisplaySubSystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.DisplaySubSystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *人像的X坐标。
   * </pre>
   *
   * <code>int32 avatarX = 1;</code>
   * @return The avatarX.
   */
  int getAvatarX();

  /**
   * <pre>
   *人像的Y坐标。
   * </pre>
   *
   * <code>int32 avatarY = 2;</code>
   * @return The avatarY.
   */
  int getAvatarY();

  /**
   * <pre>
   *人像的宽度。
   * </pre>
   *
   * <code>int32 avatarWidth = 3;</code>
   * @return The avatarWidth.
   */
  int getAvatarWidth();

  /**
   * <pre>
   *人像的高度。
   * </pre>
   *
   * <code>int32 avatarHeight = 4;</code>
   * @return The avatarHeight.
   */
  int getAvatarHeight();

  /**
   * <pre>
   *人像相机X坐标。
   * </pre>
   *
   * <code>int32 avatarCameraX = 5;</code>
   * @return The avatarCameraX.
   */
  int getAvatarCameraX();

  /**
   * <pre>
   *人像相机Y坐标。
   * </pre>
   *
   * <code>int32 avatarCameraY = 6;</code>
   * @return The avatarCameraY.
   */
  int getAvatarCameraY();

  /**
   * <pre>
   *人像相机Z坐标。
   * </pre>
   *
   * <code>int32 avatarCameraZ = 7;</code>
   * @return The avatarCameraZ.
   */
  int getAvatarCameraZ();

  /**
   * <pre>
   *背景图片网址。
   * </pre>
   *
   * <code>string backgroundImage = 8;</code>
   * @return The backgroundImage.
   */
  java.lang.String getBackgroundImage();
  /**
   * <pre>
   *背景图片网址。
   * </pre>
   *
   * <code>string backgroundImage = 8;</code>
   * @return The bytes for backgroundImage.
   */
  com.google.protobuf.ByteString
      getBackgroundImageBytes();

  /**
   * <pre>
   *窗口X坐标。
   * </pre>
   *
   * <code>int32 windowX = 9;</code>
   * @return The windowX.
   */
  int getWindowX();

  /**
   * <pre>
   *窗口Y坐标。
   * </pre>
   *
   * <code>int32 windowY = 10;</code>
   * @return The windowY.
   */
  int getWindowY();

  /**
   * <pre>
   *网页地址。
   * </pre>
   *
   * <code>string webApplicationUrl = 11;</code>
   * @return The webApplicationUrl.
   */
  java.lang.String getWebApplicationUrl();
  /**
   * <pre>
   *网页地址。
   * </pre>
   *
   * <code>string webApplicationUrl = 11;</code>
   * @return The bytes for webApplicationUrl.
   */
  com.google.protobuf.ByteString
      getWebApplicationUrlBytes();

  /**
   * <pre>
   *网页容器。
   * </pre>
   *
   * <code>string webApplicationContainer = 12;</code>
   * @return The webApplicationContainer.
   */
  java.lang.String getWebApplicationContainer();
  /**
   * <pre>
   *网页容器。
   * </pre>
   *
   * <code>string webApplicationContainer = 12;</code>
   * @return The bytes for webApplicationContainer.
   */
  com.google.protobuf.ByteString
      getWebApplicationContainerBytes();

  /**
   * <pre>
   *网页容器窗口是否可见。
   * </pre>
   *
   * <code>bool webApplicationWindowVisible = 13;</code>
   * @return The webApplicationWindowVisible.
   */
  boolean getWebApplicationWindowVisible();

  /**
   * <pre>
   *人像引擎。
   * </pre>
   *
   * <code>string avatarEngine = 14;</code>
   * @return The avatarEngine.
   */
  java.lang.String getAvatarEngine();
  /**
   * <pre>
   *人像引擎。
   * </pre>
   *
   * <code>string avatarEngine = 14;</code>
   * @return The bytes for avatarEngine.
   */
  com.google.protobuf.ByteString
      getAvatarEngineBytes();

  /**
   * <pre>
   *新版三维人像引擎的相机X坐标。
   * </pre>
   *
   * <code>float iBotEx3DEngineCameraX = 15;</code>
   * @return The iBotEx3DEngineCameraX.
   */
  float getIBotEx3DEngineCameraX();

  /**
   * <pre>
   *新版三维人像引擎的相机Y坐标。
   * </pre>
   *
   * <code>float iBotEx3DEngineCameraY = 16;</code>
   * @return The iBotEx3DEngineCameraY.
   */
  float getIBotEx3DEngineCameraY();

  /**
   * <pre>
   *新版三维人像引擎的相机Z坐标。
   * </pre>
   *
   * <code>float iBotEx3DEngineCameraZ = 17;</code>
   * @return The iBotEx3DEngineCameraZ.
   */
  float getIBotEx3DEngineCameraZ();

  /**
   * <pre>
   *新版三维人像引擎的相机参数。
   * </pre>
   *
   * <code>float iBotEx3DEngineCameraPitch = 18;</code>
   * @return The iBotEx3DEngineCameraPitch.
   */
  float getIBotEx3DEngineCameraPitch();

  /**
   * <pre>
   *新版三维人像引擎的相机参数。
   * </pre>
   *
   * <code>float iBotEx3DEngineCameraRoll = 19;</code>
   * @return The iBotEx3DEngineCameraRoll.
   */
  float getIBotEx3DEngineCameraRoll();

  /**
   * <pre>
   *新版三维人像引擎的相机参数。
   * </pre>
   *
   * <code>float iBotEx3DEngineCameraYaw = 20;</code>
   * @return The iBotEx3DEngineCameraYaw.
   */
  float getIBotEx3DEngineCameraYaw();

  /**
   * <pre>
   *闲时动作。
   * </pre>
   *
   * <code>string idleAction = 21;</code>
   * @return The idleAction.
   */
  java.lang.String getIdleAction();
  /**
   * <pre>
   *闲时动作。
   * </pre>
   *
   * <code>string idleAction = 21;</code>
   * @return The bytes for idleAction.
   */
  com.google.protobuf.ByteString
      getIdleActionBytes();

  /**
   * <pre>
   *是否启用多点触摸。
   * </pre>
   *
   * <code>bool multiTouchEnabled = 22;</code>
   * @return The multiTouchEnabled.
   */
  boolean getMultiTouchEnabled();

  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   * @return Whether the reportFaceRecognizeResultMessage field is set.
   */
  boolean hasReportFaceRecognizeResultMessage();
  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   * @return The reportFaceRecognizeResultMessage.
   */
  com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq getReportFaceRecognizeResultMessage();
  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   */
  com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqOrBuilder getReportFaceRecognizeResultMessageOrBuilder();
}
