// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DisplaySubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public final class DisplaySubSystemMessageProtos {
  private DisplaySubSystemMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_DisplaySubSystemMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_DisplaySubSystemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035DisplaySubSystemMessage.proto\022\033com.stu" +
      "pidbeauty.hxlauncher\032\"ReportFaceRecogniz" +
      "eResultReq.proto\"\264\005\n\027DisplaySubSystemMes" +
      "sage\022\017\n\007avatarX\030\001 \001(\005\022\017\n\007avatarY\030\002 \001(\005\022\023" +
      "\n\013avatarWidth\030\003 \001(\005\022\024\n\014avatarHeight\030\004 \001(" +
      "\005\022\025\n\ravatarCameraX\030\005 \001(\005\022\025\n\ravatarCamera" +
      "Y\030\006 \001(\005\022\025\n\ravatarCameraZ\030\007 \001(\005\022\027\n\017backgr" +
      "oundImage\030\010 \001(\t\022\017\n\007windowX\030\t \001(\005\022\017\n\007wind" +
      "owY\030\n \001(\005\022\031\n\021webApplicationUrl\030\013 \001(\t\022\037\n\027" +
      "webApplicationContainer\030\014 \001(\t\022#\n\033webAppl" +
      "icationWindowVisible\030\r \001(\010\022\024\n\014avatarEngi" +
      "ne\030\016 \001(\t\022\035\n\025iBotEx3DEngineCameraX\030\017 \001(\002\022" +
      "\035\n\025iBotEx3DEngineCameraY\030\020 \001(\002\022\035\n\025iBotEx" +
      "3DEngineCameraZ\030\021 \001(\002\022!\n\031iBotEx3DEngineC" +
      "ameraPitch\030\022 \001(\002\022 \n\030iBotEx3DEngineCamera" +
      "Roll\030\023 \001(\002\022\037\n\027iBotEx3DEngineCameraYaw\030\024 " +
      "\001(\002\022\022\n\nidleAction\030\025 \001(\t\022\031\n\021multiTouchEna" +
      "bled\030\026 \001(\010\022c\n reportFaceRecognizeResultM" +
      "essage\030\027 \001(\01329.com.stupidbeauty.hxlaunch" +
      "er.ReportFaceRecognizeResultReqB>\n\033com.s" +
      "tupidbeauty.hxlauncherB\035DisplaySubSystem" +
      "MessageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_DisplaySubSystemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_DisplaySubSystemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_DisplaySubSystemMessage_descriptor,
        new java.lang.String[] { "AvatarX", "AvatarY", "AvatarWidth", "AvatarHeight", "AvatarCameraX", "AvatarCameraY", "AvatarCameraZ", "BackgroundImage", "WindowX", "WindowY", "WebApplicationUrl", "WebApplicationContainer", "WebApplicationWindowVisible", "AvatarEngine", "IBotEx3DEngineCameraX", "IBotEx3DEngineCameraY", "IBotEx3DEngineCameraZ", "IBotEx3DEngineCameraPitch", "IBotEx3DEngineCameraRoll", "IBotEx3DEngineCameraYaw", "IdleAction", "MultiTouchEnabled", "ReportFaceRecognizeResultMessage", });
    com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
