// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HxLauncherFunctionName.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf enum {@code com.stupidbeauty.hxlauncher.HxLauncherFunctionName}
 */
public enum HxLauncherFunctionName
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *无意义。
   * </pre>
   *
   * <code>Nonsense = 0;</code>
   */
  Nonsense(0),
  /**
   * <pre>
   *注册信息。
   * </pre>
   *
   * <code>RegisterInformation = 1;</code>
   */
  RegisterInformation(1),
  /**
   * <pre>
   *注册结果。
   * </pre>
   *
   * <code>RegisterResult = 2;</code>
   */
  RegisterResult(2),
  /**
   * <pre>
   *报告语音识别进程的错误。
   * </pre>
   *
   * <code>ReportVoiceRecognizeProcessError = 3;</code>
   */
  ReportVoiceRecognizeProcessError(3),
  /**
   * <pre>
   *报告语音输入设备源。
   * </pre>
   *
   * <code>ReportAudioSoundSource = 4;</code>
   */
  ReportAudioSoundSource(4),
  /**
   * <pre>
   *终止嘴型序列。
   * </pre>
   *
   * <code>CancelPhenem = 5;</code>
   */
  CancelPhenem(5),
  /**
   * <pre>
   *设置人像的背景图片。
   * </pre>
   *
   * <code>SetAvatarBackgroundImage = 6;</code>
   */
  SetAvatarBackgroundImage(6),
  /**
   * <pre>
   *设置三维人像渲染相机的位置及角度。
   * </pre>
   *
   * <code>Set3DEngineCameraPositionRotation = 7;</code>
   */
  Set3DEngineCameraPositionRotation(7),
  /**
   * <pre>
   *报告，听到了人声。
   * </pre>
   *
   * <code>ReportHeardHumanVoice = 27;</code>
   */
  ReportHeardHumanVoice(27),
  /**
   * <pre>
   *报告，被唤醒。
   * </pre>
   *
   * <code>ReportWakedUp = 28;</code>
   */
  ReportWakedUp(28),
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>ReportAccurateVoiceCommand = 30;</code>
   */
  ReportAccurateVoiceCommand(30),
  /**
   * <pre>
   *显示错误码页面。
   * </pre>
   *
   * <code>ShowErrorCodePage = 52;</code>
   */
  ShowErrorCodePage(52),
  /**
   * <pre>
   *最小化．
   * </pre>
   *
   * <code>Minimize = 53;</code>
   */
  Minimize(53),
  /**
   * <pre>
   *显示开发者工具。
   * </pre>
   *
   * <code>ShowDeveloperTools = 54;</code>
   */
  ShowDeveloperTools(54),
  /**
   * <pre>
   *报告，窗口被激活。
   * </pre>
   *
   * <code>ReportWindowActivated = 55;</code>
   */
  ReportWindowActivated(55),
  /**
   * <pre>
   *显示设置页面。
   * </pre>
   *
   * <code>ShowSettingsPage = 57;</code>
   */
  ShowSettingsPage(57),
  /**
   * <pre>
   *恢复窗口。
   * </pre>
   *
   * <code>RestoreWindow = 58;</code>
   */
  RestoreWindow(58),
  /**
   * <pre>
   *结束连续语音识别。
   * </pre>
   *
   * <code>FinishVoiceRecognize = 59;</code>
   */
  FinishVoiceRecognize(59),
  /**
   * <pre>
   *在线语音合成。
   * </pre>
   *
   * <code>OnlineTts = 60;</code>
   */
  OnlineTts(60),
  /**
   * <pre>
   *停止语音识别。
   * </pre>
   *
   * <code>StopVoiceRecognize = 61;</code>
   */
  StopVoiceRecognize(61),
  /**
   * <pre>
   *报告宏执行结束。
   * </pre>
   *
   * <code>ReportMacroFinished = 62;</code>
   */
  ReportMacroFinished(62),
  /**
   * <pre>
   *报告宏语音执行结束。
   * </pre>
   *
   * <code>ReportMacroVoiceFinished = 63;</code>
   */
  ReportMacroVoiceFinished(63),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *无意义。
   * </pre>
   *
   * <code>Nonsense = 0;</code>
   */
  public static final int Nonsense_VALUE = 0;
  /**
   * <pre>
   *注册信息。
   * </pre>
   *
   * <code>RegisterInformation = 1;</code>
   */
  public static final int RegisterInformation_VALUE = 1;
  /**
   * <pre>
   *注册结果。
   * </pre>
   *
   * <code>RegisterResult = 2;</code>
   */
  public static final int RegisterResult_VALUE = 2;
  /**
   * <pre>
   *报告语音识别进程的错误。
   * </pre>
   *
   * <code>ReportVoiceRecognizeProcessError = 3;</code>
   */
  public static final int ReportVoiceRecognizeProcessError_VALUE = 3;
  /**
   * <pre>
   *报告语音输入设备源。
   * </pre>
   *
   * <code>ReportAudioSoundSource = 4;</code>
   */
  public static final int ReportAudioSoundSource_VALUE = 4;
  /**
   * <pre>
   *终止嘴型序列。
   * </pre>
   *
   * <code>CancelPhenem = 5;</code>
   */
  public static final int CancelPhenem_VALUE = 5;
  /**
   * <pre>
   *设置人像的背景图片。
   * </pre>
   *
   * <code>SetAvatarBackgroundImage = 6;</code>
   */
  public static final int SetAvatarBackgroundImage_VALUE = 6;
  /**
   * <pre>
   *设置三维人像渲染相机的位置及角度。
   * </pre>
   *
   * <code>Set3DEngineCameraPositionRotation = 7;</code>
   */
  public static final int Set3DEngineCameraPositionRotation_VALUE = 7;
  /**
   * <pre>
   *报告，听到了人声。
   * </pre>
   *
   * <code>ReportHeardHumanVoice = 27;</code>
   */
  public static final int ReportHeardHumanVoice_VALUE = 27;
  /**
   * <pre>
   *报告，被唤醒。
   * </pre>
   *
   * <code>ReportWakedUp = 28;</code>
   */
  public static final int ReportWakedUp_VALUE = 28;
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>ReportAccurateVoiceCommand = 30;</code>
   */
  public static final int ReportAccurateVoiceCommand_VALUE = 30;
  /**
   * <pre>
   *显示错误码页面。
   * </pre>
   *
   * <code>ShowErrorCodePage = 52;</code>
   */
  public static final int ShowErrorCodePage_VALUE = 52;
  /**
   * <pre>
   *最小化．
   * </pre>
   *
   * <code>Minimize = 53;</code>
   */
  public static final int Minimize_VALUE = 53;
  /**
   * <pre>
   *显示开发者工具。
   * </pre>
   *
   * <code>ShowDeveloperTools = 54;</code>
   */
  public static final int ShowDeveloperTools_VALUE = 54;
  /**
   * <pre>
   *报告，窗口被激活。
   * </pre>
   *
   * <code>ReportWindowActivated = 55;</code>
   */
  public static final int ReportWindowActivated_VALUE = 55;
  /**
   * <pre>
   *显示设置页面。
   * </pre>
   *
   * <code>ShowSettingsPage = 57;</code>
   */
  public static final int ShowSettingsPage_VALUE = 57;
  /**
   * <pre>
   *恢复窗口。
   * </pre>
   *
   * <code>RestoreWindow = 58;</code>
   */
  public static final int RestoreWindow_VALUE = 58;
  /**
   * <pre>
   *结束连续语音识别。
   * </pre>
   *
   * <code>FinishVoiceRecognize = 59;</code>
   */
  public static final int FinishVoiceRecognize_VALUE = 59;
  /**
   * <pre>
   *在线语音合成。
   * </pre>
   *
   * <code>OnlineTts = 60;</code>
   */
  public static final int OnlineTts_VALUE = 60;
  /**
   * <pre>
   *停止语音识别。
   * </pre>
   *
   * <code>StopVoiceRecognize = 61;</code>
   */
  public static final int StopVoiceRecognize_VALUE = 61;
  /**
   * <pre>
   *报告宏执行结束。
   * </pre>
   *
   * <code>ReportMacroFinished = 62;</code>
   */
  public static final int ReportMacroFinished_VALUE = 62;
  /**
   * <pre>
   *报告宏语音执行结束。
   * </pre>
   *
   * <code>ReportMacroVoiceFinished = 63;</code>
   */
  public static final int ReportMacroVoiceFinished_VALUE = 63;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HxLauncherFunctionName valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static HxLauncherFunctionName forNumber(int value) {
    switch (value) {
      case 0: return Nonsense;
      case 1: return RegisterInformation;
      case 2: return RegisterResult;
      case 3: return ReportVoiceRecognizeProcessError;
      case 4: return ReportAudioSoundSource;
      case 5: return CancelPhenem;
      case 6: return SetAvatarBackgroundImage;
      case 7: return Set3DEngineCameraPositionRotation;
      case 27: return ReportHeardHumanVoice;
      case 28: return ReportWakedUp;
      case 30: return ReportAccurateVoiceCommand;
      case 52: return ShowErrorCodePage;
      case 53: return Minimize;
      case 54: return ShowDeveloperTools;
      case 55: return ReportWindowActivated;
      case 57: return ShowSettingsPage;
      case 58: return RestoreWindow;
      case 59: return FinishVoiceRecognize;
      case 60: return OnlineTts;
      case 61: return StopVoiceRecognize;
      case 62: return ReportMacroFinished;
      case 63: return ReportMacroVoiceFinished;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HxLauncherFunctionName>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HxLauncherFunctionName> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HxLauncherFunctionName>() {
          public HxLauncherFunctionName findValueByNumber(int number) {
            return HxLauncherFunctionName.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.HxLauncherFunctionNameProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final HxLauncherFunctionName[] VALUES = values();

  public static HxLauncherFunctionName valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HxLauncherFunctionName(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.stupidbeauty.hxlauncher.HxLauncherFunctionName)
}

