// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HxLauncherFunctionName.proto

package com.stupidbeauty.hxlauncher;

public final class HxLauncherFunctionNameProtos {
  private HxLauncherFunctionNameProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034HxLauncherFunctionName.proto\022\033com.stup" +
      "idbeauty.hxlauncher*\263\004\n\026HxLauncherFuncti" +
      "onName\022\014\n\010Nonsense\020\000\022\027\n\023RegisterInformat" +
      "ion\020\001\022\022\n\016RegisterResult\020\002\022$\n ReportVoice" +
      "RecognizeProcessError\020\003\022\032\n\026ReportAudioSo" +
      "undSource\020\004\022\020\n\014CancelPhenem\020\005\022\034\n\030SetAvat" +
      "arBackgroundImage\020\006\022%\n!Set3DEngineCamera" +
      "PositionRotation\020\007\022\031\n\025ReportHeardHumanVo" +
      "ice\020\033\022\021\n\rReportWakedUp\020\034\022\036\n\032ReportAccura" +
      "teVoiceCommand\020\036\022\025\n\021ShowErrorCodePage\0204\022" +
      "\014\n\010Minimize\0205\022\026\n\022ShowDeveloperTools\0206\022\031\n" +
      "\025ReportWindowActivated\0207\022\024\n\020ShowSettings" +
      "Page\0209\022\021\n\rRestoreWindow\020:\022\030\n\024FinishVoice" +
      "Recognize\020;\022\r\n\tOnlineTts\020<\022\026\n\022StopVoiceR" +
      "ecognize\020=\022\027\n\023ReportMacroFinished\020>\022\034\n\030R" +
      "eportMacroVoiceFinished\020?B=\n\033com.stupidb" +
      "eauty.hxlauncherB\034HxLauncherFunctionName" +
      "ProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
