// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HxLauncherIconType.proto

package com.stupidbeauty.hxlauncher;

public final class HxLauncherIconTypeProtos {
  private HxLauncherIconTypeProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030HxLauncherIconType.proto\022\033com.stupidbe" +
      "auty.hxlauncher*Z\n\022HxLauncherIconType\022\024\n" +
      "\020NonsenseIconType\020\000\022\026\n\022PbShortcutIconTyp" +
      "e\020\001\022\026\n\022PbActivityIconType\020\002B9\n\033com.stupi" +
      "dbeauty.hxlauncherB\030HxLauncherIconTypePr" +
      "otosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
