// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HxLauncherMessage.proto

package com.stupidbeauty.hxlauncher;

public interface HxLauncherMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.HxLauncherMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.HxLauncherFunctionName functionName = 1;</code>
   * @return The enum numeric value on the wire for functionName.
   */
  int getFunctionNameValue();
  /**
   * <pre>
   *要执行的函数名字。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.HxLauncherFunctionName functionName = 1;</code>
   * @return The functionName.
   */
  com.stupidbeauty.hxlauncher.HxLauncherFunctionName getFunctionName();

  /**
   * <pre>
   *注册信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.RegisterInformationMessage registerInformationMessage = 2;</code>
   * @return Whether the registerInformationMessage field is set.
   */
  boolean hasRegisterInformationMessage();
  /**
   * <pre>
   *注册信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.RegisterInformationMessage registerInformationMessage = 2;</code>
   * @return The registerInformationMessage.
   */
  com.stupidbeauty.hxlauncher.RegisterInformationMessageProtos.RegisterInformationMessage getRegisterInformationMessage();
  /**
   * <pre>
   *注册信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.RegisterInformationMessage registerInformationMessage = 2;</code>
   */
  com.stupidbeauty.hxlauncher.RegisterInformationMessageProtos.RegisterInformationMessageOrBuilder getRegisterInformationMessageOrBuilder();

  /**
   * <pre>
   *随机填充的字符串，用于增加加密结果的变化。
   * </pre>
   *
   * <code>string randomPadding = 3;</code>
   * @return The randomPadding.
   */
  java.lang.String getRandomPadding();
  /**
   * <pre>
   *随机填充的字符串，用于增加加密结果的变化。
   * </pre>
   *
   * <code>string randomPadding = 3;</code>
   * @return The bytes for randomPadding.
   */
  com.google.protobuf.ByteString
      getRandomPaddingBytes();

  /**
   * <pre>
   *客户端连接编号。在回复消息时找到正确的客户端连接。
   * </pre>
   *
   * <code>int64 clientConnectionId = 4;</code>
   * @return The clientConnectionId.
   */
  long getClientConnectionId();

  /**
   * <pre>
   *报告注册结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.RegisterResultMessage registerResultMessage = 5;</code>
   * @return Whether the registerResultMessage field is set.
   */
  boolean hasRegisterResultMessage();
  /**
   * <pre>
   *报告注册结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.RegisterResultMessage registerResultMessage = 5;</code>
   * @return The registerResultMessage.
   */
  com.stupidbeauty.hxlauncher.RegisterResultMessage getRegisterResultMessage();
  /**
   * <pre>
   *报告注册结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.RegisterResultMessage registerResultMessage = 5;</code>
   */
  com.stupidbeauty.hxlauncher.RegisterResultMessageOrBuilder getRegisterResultMessageOrBuilder();

  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   * @return Whether the reportFaceRecognizeResultMessage field is set.
   */
  boolean hasReportFaceRecognizeResultMessage();
  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   * @return The reportFaceRecognizeResultMessage.
   */
  com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq getReportFaceRecognizeResultMessage();
  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   */
  com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqOrBuilder getReportFaceRecognizeResultMessageOrBuilder();

  /**
   * <pre>
   *消息的时间戳。
   * </pre>
   *
   * <code>int64 timeStamp = 31;</code>
   * @return The timeStamp.
   */
  long getTimeStamp();

  /**
   * <pre>
   *开关，是否允许对网页的多点触控。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReq SetMultiTouchEnabledMessage = 35;</code>
   * @return Whether the setMultiTouchEnabledMessage field is set.
   */
  boolean hasSetMultiTouchEnabledMessage();
  /**
   * <pre>
   *开关，是否允许对网页的多点触控。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReq SetMultiTouchEnabledMessage = 35;</code>
   * @return The setMultiTouchEnabledMessage.
   */
  com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReq getSetMultiTouchEnabledMessage();
  /**
   * <pre>
   *开关，是否允许对网页的多点触控。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReq SetMultiTouchEnabledMessage = 35;</code>
   */
  com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReqOrBuilder getSetMultiTouchEnabledMessageOrBuilder();

  /**
   * <pre>
   *显示错误码页面。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ShowErrorCodePageReq showErrorCodePageMessage = 36;</code>
   * @return Whether the showErrorCodePageMessage field is set.
   */
  boolean hasShowErrorCodePageMessage();
  /**
   * <pre>
   *显示错误码页面。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ShowErrorCodePageReq showErrorCodePageMessage = 36;</code>
   * @return The showErrorCodePageMessage.
   */
  com.stupidbeauty.hxlauncher.ShowErrorCodePageReq getShowErrorCodePageMessage();
  /**
   * <pre>
   *显示错误码页面。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ShowErrorCodePageReq showErrorCodePageMessage = 36;</code>
   */
  com.stupidbeauty.hxlauncher.ShowErrorCodePageReqOrBuilder getShowErrorCodePageMessageOrBuilder();

  /**
   * <pre>
   *报告错误码。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportErrorCodeReq reportErrorCodeMessage = 37;</code>
   * @return Whether the reportErrorCodeMessage field is set.
   */
  boolean hasReportErrorCodeMessage();
  /**
   * <pre>
   *报告错误码。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportErrorCodeReq reportErrorCodeMessage = 37;</code>
   * @return The reportErrorCodeMessage.
   */
  com.stupidbeauty.hxlauncher.ReportErrorCodeReq getReportErrorCodeMessage();
  /**
   * <pre>
   *报告错误码。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportErrorCodeReq reportErrorCodeMessage = 37;</code>
   */
  com.stupidbeauty.hxlauncher.ReportErrorCodeReqOrBuilder getReportErrorCodeMessageOrBuilder();

  /**
   * <pre>
   *在线语音合成消息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.OnlineTtsReq onlineTtsMessage = 38;</code>
   * @return Whether the onlineTtsMessage field is set.
   */
  boolean hasOnlineTtsMessage();
  /**
   * <pre>
   *在线语音合成消息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.OnlineTtsReq onlineTtsMessage = 38;</code>
   * @return The onlineTtsMessage.
   */
  com.stupidbeauty.hxlauncher.OnlineTtsReq getOnlineTtsMessage();
  /**
   * <pre>
   *在线语音合成消息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.OnlineTtsReq onlineTtsMessage = 38;</code>
   */
  com.stupidbeauty.hxlauncher.OnlineTtsReqOrBuilder getOnlineTtsMessageOrBuilder();

  /**
   * <pre>
   *报告宏执行完毕。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportMacroFinishedReq reportMacroFinishedMessage = 39;</code>
   * @return Whether the reportMacroFinishedMessage field is set.
   */
  boolean hasReportMacroFinishedMessage();
  /**
   * <pre>
   *报告宏执行完毕。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportMacroFinishedReq reportMacroFinishedMessage = 39;</code>
   * @return The reportMacroFinishedMessage.
   */
  com.stupidbeauty.hxlauncher.ReportMacroFinishedReq getReportMacroFinishedMessage();
  /**
   * <pre>
   *报告宏执行完毕。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportMacroFinishedReq reportMacroFinishedMessage = 39;</code>
   */
  com.stupidbeauty.hxlauncher.ReportMacroFinishedReqOrBuilder getReportMacroFinishedMessageOrBuilder();
}
