// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HxLauncherIconType.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf enum {@code com.stupidbeauty.hxlauncher.HxLauncherIconType}
 */
public enum HxLauncherIconType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *无意义。
   * </pre>
   *
   * <code>NonsenseIconType = 0;</code>
   */
  NonsenseIconType(0),
  /**
   * <pre>
   *快捷方式。
   * </pre>
   *
   * <code>PbShortcutIconType = 1;</code>
   */
  PbShortcutIconType(1),
  /**
   * <pre>
   *活动。
   * </pre>
   *
   * <code>PbActivityIconType = 2;</code>
   */
  PbActivityIconType(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *无意义。
   * </pre>
   *
   * <code>NonsenseIconType = 0;</code>
   */
  public static final int NonsenseIconType_VALUE = 0;
  /**
   * <pre>
   *快捷方式。
   * </pre>
   *
   * <code>PbShortcutIconType = 1;</code>
   */
  public static final int PbShortcutIconType_VALUE = 1;
  /**
   * <pre>
   *活动。
   * </pre>
   *
   * <code>PbActivityIconType = 2;</code>
   */
  public static final int PbActivityIconType_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HxLauncherIconType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static HxLauncherIconType forNumber(int value) {
    switch (value) {
      case 0: return NonsenseIconType;
      case 1: return PbShortcutIconType;
      case 2: return PbActivityIconType;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HxLauncherIconType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HxLauncherIconType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HxLauncherIconType>() {
          public HxLauncherIconType findValueByNumber(int number) {
            return HxLauncherIconType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final HxLauncherIconType[] VALUES = values();

  public static HxLauncherIconType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HxLauncherIconType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.stupidbeauty.hxlauncher.HxLauncherIconType)
}

