// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HxLauncherMessage.proto

package com.stupidbeauty.hxlauncher;

public final class HxLauncherMessageProtos {
  private HxLauncherMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_HxLauncherMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_HxLauncherMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027HxLauncherMessage.proto\022\033com.stupidbea" +
      "uty.hxlauncher\032\034HxLauncherFunctionName.p" +
      "roto\032\"ReportFaceRecognizeResultReq.proto" +
      "\032\022OnlineTtsReq.proto\032\030ReportErrorCodeReq" +
      ".proto\032\035SetMultiTouchEnabledReq.proto\032\032S" +
      "howErrorCodePageReq.proto\032\034ReportMacroFi" +
      "nishedReq.proto\032 RegisterInformationMess" +
      "age.proto\032\033RegisterResultMessage.proto\"\330" +
      "\006\n\021HxLauncherMessage\022I\n\014functionName\030\001 \001" +
      "(\01623.com.stupidbeauty.hxlauncher.HxLaunc" +
      "herFunctionName\022[\n\032registerInformationMe" +
      "ssage\030\002 \001(\01327.com.stupidbeauty.hxlaunche" +
      "r.RegisterInformationMessage\022\025\n\rrandomPa" +
      "dding\030\003 \001(\t\022\032\n\022clientConnectionId\030\004 \001(\003\022" +
      "Q\n\025registerResultMessage\030\005 \001(\01322.com.stu" +
      "pidbeauty.hxlauncher.RegisterResultMessa" +
      "ge\022c\n reportFaceRecognizeResultMessage\030\027" +
      " \001(\01329.com.stupidbeauty.hxlauncher.Repor" +
      "tFaceRecognizeResultReq\022\021\n\ttimeStamp\030\037 \001" +
      "(\003\022Y\n\033SetMultiTouchEnabledMessage\030# \001(\0132" +
      "4.com.stupidbeauty.hxlauncher.SetMultiTo" +
      "uchEnabledReq\022S\n\030showErrorCodePageMessag" +
      "e\030$ \001(\01321.com.stupidbeauty.hxlauncher.Sh" +
      "owErrorCodePageReq\022O\n\026reportErrorCodeMes" +
      "sage\030% \001(\0132/.com.stupidbeauty.hxlauncher" +
      ".ReportErrorCodeReq\022C\n\020onlineTtsMessage\030" +
      "& \001(\0132).com.stupidbeauty.hxlauncher.Onli" +
      "neTtsReq\022W\n\032reportMacroFinishedMessage\030\'" +
      " \001(\01323.com.stupidbeauty.hxlauncher.Repor" +
      "tMacroFinishedReqB:\n\033com.stupidbeauty.hx" +
      "launcherB\027HxLauncherMessageProtosH\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.HxLauncherFunctionNameProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.OnlineTtsReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ShowErrorCodePageReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.RegisterInformationMessageProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.RegisterResultMessageProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_HxLauncherMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_HxLauncherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_HxLauncherMessage_descriptor,
        new java.lang.String[] { "FunctionName", "RegisterInformationMessage", "RandomPadding", "ClientConnectionId", "RegisterResultMessage", "ReportFaceRecognizeResultMessage", "TimeStamp", "SetMultiTouchEnabledMessage", "ShowErrorCodePageMessage", "ReportErrorCodeMessage", "OnlineTtsMessage", "ReportMacroFinishedMessage", });
    com.stupidbeauty.hxlauncher.HxLauncherFunctionNameProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.OnlineTtsReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ShowErrorCodePageReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.RegisterInformationMessageProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.RegisterResultMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
