// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LicenseSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public interface LicenseSubSystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.LicenseSubSystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *许可证服务器的网址。
   * </pre>
   *
   * <code>string licenseServerUrl = 1;</code>
   * @return The licenseServerUrl.
   */
  java.lang.String getLicenseServerUrl();
  /**
   * <pre>
   *许可证服务器的网址。
   * </pre>
   *
   * <code>string licenseServerUrl = 1;</code>
   * @return The bytes for licenseServerUrl.
   */
  com.google.protobuf.ByteString
      getLicenseServerUrlBytes();

  /**
   * <pre>
   *摄像头子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.CameraSubSystemMessage cameraSubSystemMessage = 2;</code>
   * @return Whether the cameraSubSystemMessage field is set.
   */
  boolean hasCameraSubSystemMessage();
  /**
   * <pre>
   *摄像头子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.CameraSubSystemMessage cameraSubSystemMessage = 2;</code>
   * @return The cameraSubSystemMessage.
   */
  com.stupidbeauty.hxlauncher.CameraSubSystemMessage getCameraSubSystemMessage();
  /**
   * <pre>
   *摄像头子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.CameraSubSystemMessage cameraSubSystemMessage = 2;</code>
   */
  com.stupidbeauty.hxlauncher.CameraSubSystemMessageOrBuilder getCameraSubSystemMessageOrBuilder();

  /**
   * <pre>
   *显示器子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.DisplaySubSystemMessage displaySubSystemMessage = 3;</code>
   * @return Whether the displaySubSystemMessage field is set.
   */
  boolean hasDisplaySubSystemMessage();
  /**
   * <pre>
   *显示器子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.DisplaySubSystemMessage displaySubSystemMessage = 3;</code>
   * @return The displaySubSystemMessage.
   */
  com.stupidbeauty.hxlauncher.DisplaySubSystemMessage getDisplaySubSystemMessage();
  /**
   * <pre>
   *显示器子系统配置文件信息。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.DisplaySubSystemMessage displaySubSystemMessage = 3;</code>
   */
  com.stupidbeauty.hxlauncher.DisplaySubSystemMessageOrBuilder getDisplaySubSystemMessageOrBuilder();

  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return Whether the reportAudioSoundSourceReqMessage field is set.
   */
  boolean hasReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return The reportAudioSoundSourceReqMessage.
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder();

  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   * @return Whether the set3DEngineCameraPositionRotationMessage field is set.
   */
  boolean hasSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   * @return The set3DEngineCameraPositionRotationMessage.
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq getSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder getSet3DEngineCameraPositionRotationMessageOrBuilder();
}
