// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogicControlSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public final class LogicControlSubSystemMessageProtos {
  private LogicControlSubSystemMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_LogicControlSubSystemMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_LogicControlSubSystemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"LogicControlSubSystemMessage.proto\022\033co" +
      "m.stupidbeauty.hxlauncher\"\315\002\n\034LogicContr" +
      "olSubSystemMessage\022\026\n\016webSocketDebug\030\001 \001" +
      "(\010\022\023\n\013aiEngineUrl\030\002 \001(\t\022\033\n\023aiEngineUrlCl" +
      "eanTts\030\003 \001(\t\022\034\n\024aiEngineUrlWithMacro\030\004 \001" +
      "(\t\0220\n(aiEngineUrlIBotWithMacroMultipleLa" +
      "nguage\030\005 \001(\t\022\030\n\020printerServiceIp\030\006 \001(\t\022\033" +
      "\n\023cardReaderServiceIp\030\007 \001(\t\022\024\n\014controlle" +
      "rIp\030\010 \001(\t\022\031\n\021heartbeatStrategy\030\t \001(\t\022+\n#" +
      "displaySubSystemAvatarTimerInterval\030\013 \001(" +
      "\005BC\n\033com.stupidbeauty.hxlauncherB\"LogicC" +
      "ontrolSubSystemMessageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_stupidbeauty_hxlauncher_LogicControlSubSystemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_LogicControlSubSystemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_LogicControlSubSystemMessage_descriptor,
        new java.lang.String[] { "WebSocketDebug", "AiEngineUrl", "AiEngineUrlCleanTts", "AiEngineUrlWithMacro", "AiEngineUrlIBotWithMacroMultipleLanguage", "PrinterServiceIp", "CardReaderServiceIp", "ControllerIp", "HeartbeatStrategy", "DisplaySubSystemAvatarTimerInterval", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
