// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MicrophoneSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public interface MicrophoneSubSystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.MicrophoneSubSystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *是否使用精确语音指令列表。
   * </pre>
   *
   * <code>bool accurateVoiceCommandShortCut = 1;</code>
   * @return The accurateVoiceCommandShortCut.
   */
  boolean getAccurateVoiceCommandShortCut();

  /**
   * <pre>
   *存档式录音的上传地址。
   * </pre>
   *
   * <code>string archiveSoundRecordUploadUrl = 2;</code>
   * @return The archiveSoundRecordUploadUrl.
   */
  java.lang.String getArchiveSoundRecordUploadUrl();
  /**
   * <pre>
   *存档式录音的上传地址。
   * </pre>
   *
   * <code>string archiveSoundRecordUploadUrl = 2;</code>
   * @return The bytes for archiveSoundRecordUploadUrl.
   */
  com.google.protobuf.ByteString
      getArchiveSoundRecordUploadUrlBytes();

  /**
   * <pre>
   *声音来源。
   * </pre>
   *
   * <code>string audioSoundSource = 3;</code>
   * @return The audioSoundSource.
   */
  java.lang.String getAudioSoundSource();
  /**
   * <pre>
   *声音来源。
   * </pre>
   *
   * <code>string audioSoundSource = 3;</code>
   * @return The bytes for audioSoundSource.
   */
  com.google.protobuf.ByteString
      getAudioSoundSourceBytes();

  /**
   * <pre>
   *百度语音识别的APPID。
   * </pre>
   *
   * <code>string baiduSdkAppId = 4;</code>
   * @return The baiduSdkAppId.
   */
  java.lang.String getBaiduSdkAppId();
  /**
   * <pre>
   *百度语音识别的APPID。
   * </pre>
   *
   * <code>string baiduSdkAppId = 4;</code>
   * @return The bytes for baiduSdkAppId.
   */
  com.google.protobuf.ByteString
      getBaiduSdkAppIdBytes();

  /**
   * <pre>
   *报告语音识别进程错误的消息体。
   * </pre>
   *
   * <code>string baiduSdkApiKey = 5;</code>
   * @return The baiduSdkApiKey.
   */
  java.lang.String getBaiduSdkApiKey();
  /**
   * <pre>
   *报告语音识别进程错误的消息体。
   * </pre>
   *
   * <code>string baiduSdkApiKey = 5;</code>
   * @return The bytes for baiduSdkApiKey.
   */
  com.google.protobuf.ByteString
      getBaiduSdkApiKeyBytes();

  /**
   * <pre>
   *麦克风阵列的指向模式。
   * </pre>
   *
   * <code>string microphoneArrayDirectionMode = 6;</code>
   * @return The microphoneArrayDirectionMode.
   */
  java.lang.String getMicrophoneArrayDirectionMode();
  /**
   * <pre>
   *麦克风阵列的指向模式。
   * </pre>
   *
   * <code>string microphoneArrayDirectionMode = 6;</code>
   * @return The bytes for microphoneArrayDirectionMode.
   */
  com.google.protobuf.ByteString
      getMicrophoneArrayDirectionModeBytes();

  /**
   * <pre>
   *Nuance Krypton服务地址。
   * </pre>
   *
   * <code>string nuanceServiceAddress = 7;</code>
   * @return The nuanceServiceAddress.
   */
  java.lang.String getNuanceServiceAddress();
  /**
   * <pre>
   *Nuance Krypton服务地址。
   * </pre>
   *
   * <code>string nuanceServiceAddress = 7;</code>
   * @return The bytes for nuanceServiceAddress.
   */
  com.google.protobuf.ByteString
      getNuanceServiceAddressBytes();

  /**
   * <pre>
   *采样率。
   * </pre>
   *
   * <code>int32 sampleRate = 8;</code>
   * @return The sampleRate.
   */
  int getSampleRate();

  /**
   * <pre>
   *是否保存原始录音文件。
   * </pre>
   *
   * <code>bool saveRawSound = 9;</code>
   * @return The saveRawSound.
   */
  boolean getSaveRawSound();

  /**
   * <pre>
   *声翰的语音识别服务地址。
   * </pre>
   *
   * <code>string shenghanServiceAddress = 10;</code>
   * @return The shenghanServiceAddress.
   */
  java.lang.String getShenghanServiceAddress();
  /**
   * <pre>
   *声翰的语音识别服务地址。
   * </pre>
   *
   * <code>string shenghanServiceAddress = 10;</code>
   * @return The bytes for shenghanServiceAddress.
   */
  com.google.protobuf.ByteString
      getShenghanServiceAddressBytes();

  /**
   * <pre>
   *讯飞语音识别SDK的APPID。
   * </pre>
   *
   * <code>string xunfeiSdkAppId = 11;</code>
   * @return The xunfeiSdkAppId.
   */
  java.lang.String getXunfeiSdkAppId();
  /**
   * <pre>
   *讯飞语音识别SDK的APPID。
   * </pre>
   *
   * <code>string xunfeiSdkAppId = 11;</code>
   * @return The bytes for xunfeiSdkAppId.
   */
  com.google.protobuf.ByteString
      getXunfeiSdkAppIdBytes();

  /**
   * <pre>
   *讯飞语音识别SDK的SO文件目录。
   * </pre>
   *
   * <code>string xunfeiSdkLibMscSoDirectory = 12;</code>
   * @return The xunfeiSdkLibMscSoDirectory.
   */
  java.lang.String getXunfeiSdkLibMscSoDirectory();
  /**
   * <pre>
   *讯飞语音识别SDK的SO文件目录。
   * </pre>
   *
   * <code>string xunfeiSdkLibMscSoDirectory = 12;</code>
   * @return The bytes for xunfeiSdkLibMscSoDirectory.
   */
  com.google.protobuf.ByteString
      getXunfeiSdkLibMscSoDirectoryBytes();

  /**
   * <pre>
   *云知声服务地址。
   * </pre>
   *
   * <code>string yunzhishengServiceAddress = 13;</code>
   * @return The yunzhishengServiceAddress.
   */
  java.lang.String getYunzhishengServiceAddress();
  /**
   * <pre>
   *云知声服务地址。
   * </pre>
   *
   * <code>string yunzhishengServiceAddress = 13;</code>
   * @return The bytes for yunzhishengServiceAddress.
   */
  com.google.protobuf.ByteString
      getYunzhishengServiceAddressBytes();

  /**
   * <pre>
   *简体中文的语音识别引擎。
   * </pre>
   *
   * <code>string voiceRecognizeEngine = 14;</code>
   * @return The voiceRecognizeEngine.
   */
  java.lang.String getVoiceRecognizeEngine();
  /**
   * <pre>
   *简体中文的语音识别引擎。
   * </pre>
   *
   * <code>string voiceRecognizeEngine = 14;</code>
   * @return The bytes for voiceRecognizeEngine.
   */
  com.google.protobuf.ByteString
      getVoiceRecognizeEngineBytes();

  /**
   * <pre>
   *英文的语音识别引擎。
   * </pre>
   *
   * <code>string voiceRecognizeEngineEnUs = 15;</code>
   * @return The voiceRecognizeEngineEnUs.
   */
  java.lang.String getVoiceRecognizeEngineEnUs();
  /**
   * <pre>
   *英文的语音识别引擎。
   * </pre>
   *
   * <code>string voiceRecognizeEngineEnUs = 15;</code>
   * @return The bytes for voiceRecognizeEngineEnUs.
   */
  com.google.protobuf.ByteString
      getVoiceRecognizeEngineEnUsBytes();

  /**
   * <pre>
   *广东话的语音识别引擎。
   * </pre>
   *
   * <code>string voiceRecognizeEngineYueHantHk = 16;</code>
   * @return The voiceRecognizeEngineYueHantHk.
   */
  java.lang.String getVoiceRecognizeEngineYueHantHk();
  /**
   * <pre>
   *广东话的语音识别引擎。
   * </pre>
   *
   * <code>string voiceRecognizeEngineYueHantHk = 16;</code>
   * @return The bytes for voiceRecognizeEngineYueHantHk.
   */
  com.google.protobuf.ByteString
      getVoiceRecognizeEngineYueHantHkBytes();

  /**
   * <pre>
   *语音识别后端点时长。
   * </pre>
   *
   * <code>int32 vadEos = 17;</code>
   * @return The vadEos.
   */
  int getVadEos();

  /**
   * <pre>
   *谷歌云认证信息文件路径。
   * </pre>
   *
   * <code>string googleCredentialsPath = 18;</code>
   * @return The googleCredentialsPath.
   */
  java.lang.String getGoogleCredentialsPath();
  /**
   * <pre>
   *谷歌云认证信息文件路径。
   * </pre>
   *
   * <code>string googleCredentialsPath = 18;</code>
   * @return The bytes for googleCredentialsPath.
   */
  com.google.protobuf.ByteString
      getGoogleCredentialsPathBytes();

  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string candidateAudioSoundSource = 19;</code>
   * @return A list containing the candidateAudioSoundSource.
   */
  java.util.List<java.lang.String>
      getCandidateAudioSoundSourceList();
  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string candidateAudioSoundSource = 19;</code>
   * @return The count of candidateAudioSoundSource.
   */
  int getCandidateAudioSoundSourceCount();
  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string candidateAudioSoundSource = 19;</code>
   * @param index The index of the element to return.
   * @return The candidateAudioSoundSource at the given index.
   */
  java.lang.String getCandidateAudioSoundSource(int index);
  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string candidateAudioSoundSource = 19;</code>
   * @param index The index of the value to return.
   * @return The bytes of the candidateAudioSoundSource at the given index.
   */
  com.google.protobuf.ByteString
      getCandidateAudioSoundSourceBytes(int index);

  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return Whether the reportVoiceRecognizedMessage field is set.
   */
  boolean hasReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return The reportVoiceRecognizedMessage.
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder();
}
