// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public interface MonitorSubSystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *监控服务网址。
   * </pre>
   *
   * <code>string monitorServiceUrl = 1;</code>
   * @return The monitorServiceUrl.
   */
  java.lang.String getMonitorServiceUrl();
  /**
   * <pre>
   *监控服务网址。
   * </pre>
   *
   * <code>string monitorServiceUrl = 1;</code>
   * @return The bytes for monitorServiceUrl.
   */
  com.google.protobuf.ByteString
      getMonitorServiceUrlBytes();

  /**
   * <pre>
   *机器编号。
   * </pre>
   *
   * <code>string robotId = 2;</code>
   * @return The robotId.
   */
  java.lang.String getRobotId();
  /**
   * <pre>
   *机器编号。
   * </pre>
   *
   * <code>string robotId = 2;</code>
   * @return The bytes for robotId.
   */
  com.google.protobuf.ByteString
      getRobotIdBytes();

  /**
   * <pre>
   *简短的机器编码。
   * </pre>
   *
   * <code>string machineCode = 3;</code>
   * @return The machineCode.
   */
  java.lang.String getMachineCode();
  /**
   * <pre>
   *简短的机器编码。
   * </pre>
   *
   * <code>string machineCode = 3;</code>
   * @return The bytes for machineCode.
   */
  com.google.protobuf.ByteString
      getMachineCodeBytes();
}
