// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterResultMessage.proto

package com.stupidbeauty.hxlauncher;

public final class RegisterResultMessageProtos {
  private RegisterResultMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_RegisterResultMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_RegisterResultMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033RegisterResultMessage.proto\022\033com.stupi" +
      "dbeauty.hxlauncher\032\"ReportFaceRecognizeR" +
      "esultReq.proto\032\022OnlineTtsReq.proto\032\030Repo" +
      "rtErrorCodeReq.proto\032\035SetMultiTouchEnabl" +
      "edReq.proto\032\032ShowErrorCodePageReq.proto\032" +
      "\034ReportMacroFinishedReq.proto\032 RegisterI" +
      "nformationMessage.proto\"\242\006\n\025RegisterResu" +
      "ltMessage\022\017\n\007success\030\001 \001(\010\022[\n\032registerIn" +
      "formationMessage\030\002 \001(\01327.com.stupidbeaut" +
      "y.hxlauncher.RegisterInformationMessage\022" +
      "\025\n\rrandomPadding\030\003 \001(\t\022\032\n\022clientConnecti" +
      "onId\030\004 \001(\003\022Q\n\025registerResultMessage\030\005 \001(" +
      "\01322.com.stupidbeauty.hxlauncher.Register" +
      "ResultMessage\022c\n reportFaceRecognizeResu" +
      "ltMessage\030\027 \001(\01329.com.stupidbeauty.hxlau" +
      "ncher.ReportFaceRecognizeResultReq\022\021\n\tti" +
      "meStamp\030\037 \001(\003\022Y\n\033SetMultiTouchEnabledMes" +
      "sage\030# \001(\01324.com.stupidbeauty.hxlauncher" +
      ".SetMultiTouchEnabledReq\022S\n\030showErrorCod" +
      "ePageMessage\030$ \001(\01321.com.stupidbeauty.hx" +
      "launcher.ShowErrorCodePageReq\022O\n\026reportE" +
      "rrorCodeMessage\030% \001(\0132/.com.stupidbeauty" +
      ".hxlauncher.ReportErrorCodeReq\022C\n\020online" +
      "TtsMessage\030& \001(\0132).com.stupidbeauty.hxla" +
      "uncher.OnlineTtsReq\022W\n\032reportMacroFinish" +
      "edMessage\030\' \001(\01323.com.stupidbeauty.hxlau" +
      "ncher.ReportMacroFinishedReqB>\n\033com.stup" +
      "idbeauty.hxlauncherB\033RegisterResultMessa" +
      "geProtosH\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.OnlineTtsReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ShowErrorCodePageReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.RegisterInformationMessageProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_RegisterResultMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_RegisterResultMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_RegisterResultMessage_descriptor,
        new java.lang.String[] { "Success", "RegisterInformationMessage", "RandomPadding", "ClientConnectionId", "RegisterResultMessage", "ReportFaceRecognizeResultMessage", "TimeStamp", "SetMultiTouchEnabledMessage", "ShowErrorCodePageMessage", "ReportErrorCodeMessage", "OnlineTtsMessage", "ReportMacroFinishedMessage", });
    com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.OnlineTtsReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportErrorCodeReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.SetMultiTouchEnabledReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ShowErrorCodePageReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportMacroFinishedReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.RegisterInformationMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
