// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportAudioSoundSourceReq.proto

package com.stupidbeauty.hxlauncher;

public interface ReportAudioSoundSourceReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string audioSoundSource = 1;</code>
   * @return A list containing the audioSoundSource.
   */
  java.util.List<java.lang.String>
      getAudioSoundSourceList();
  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string audioSoundSource = 1;</code>
   * @return The count of audioSoundSource.
   */
  int getAudioSoundSourceCount();
  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string audioSoundSource = 1;</code>
   * @param index The index of the element to return.
   * @return The audioSoundSource at the given index.
   */
  java.lang.String getAudioSoundSource(int index);
  /**
   * <pre>
   *候选声音输入设备列表。
   * </pre>
   *
   * <code>repeated string audioSoundSource = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the audioSoundSource at the given index.
   */
  com.google.protobuf.ByteString
      getAudioSoundSourceBytes(int index);
}
