// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportWrongAnswerReq.proto

package com.stupidbeauty.hxlauncher;

public final class ReportWrongAnswerReqOuterClass {
  private ReportWrongAnswerReqOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReportWrongAnswerReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportWrongAnswerReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *!&lt;要读出的数字。
     * </pre>
     *
     * <code>uint32 numberToRead = 1;</code>
     * @return The numberToRead.
     */
    int getNumberToRead();

    /**
     * <pre>
     *!&lt;当前显示的答案
     * </pre>
     *
     * <code>string shownAnswer = 2;</code>
     * @return The shownAnswer.
     */
    java.lang.String getShownAnswer();
    /**
     * <pre>
     *!&lt;当前显示的答案
     * </pre>
     *
     * <code>string shownAnswer = 2;</code>
     * @return The bytes for shownAnswer.
     */
    com.google.protobuf.ByteString
        getShownAnswerBytes();

    /**
     * <pre>
     *!&lt;录音文件名。
     * </pre>
     *
     * <code>string recordFileName = 3;</code>
     * @return The recordFileName.
     */
    java.lang.String getRecordFileName();
    /**
     * <pre>
     *!&lt;录音文件名。
     * </pre>
     *
     * <code>string recordFileName = 3;</code>
     * @return The bytes for recordFileName.
     */
    com.google.protobuf.ByteString
        getRecordFileNameBytes();

    /**
     * <pre>
     *!&lt;录音文件内容。
     * </pre>
     *
     * <code>bytes recordFileContent = 4;</code>
     * @return The recordFileContent.
     */
    com.google.protobuf.ByteString getRecordFileContent();

    /**
     * <pre>
     *!&lt;照片文件。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
     * @return Whether the photoFile field is set.
     */
    boolean hasPhotoFile();
    /**
     * <pre>
     *!&lt;照片文件。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
     * @return The photoFile.
     */
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getPhotoFile();
    /**
     * <pre>
     *!&lt;照片文件。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
     */
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getPhotoFileOrBuilder();

    /**
     * <pre>
     *!&lt;录音文件。替代 录音文件名 和 录音文件内容
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
     * @return Whether the recordFile field is set.
     */
    boolean hasRecordFile();
    /**
     * <pre>
     *!&lt;录音文件。替代 录音文件名 和 录音文件内容
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
     * @return The recordFile.
     */
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getRecordFile();
    /**
     * <pre>
     *!&lt;录音文件。替代 录音文件名 和 录音文件内容
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
     */
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getRecordFileOrBuilder();

    /**
     * <pre>
     *!&lt;原始识别结果。
     * </pre>
     *
     * <code>string originalRecognizeResult = 10;</code>
     * @return The originalRecognizeResult.
     */
    java.lang.String getOriginalRecognizeResult();
    /**
     * <pre>
     *!&lt;原始识别结果。
     * </pre>
     *
     * <code>string originalRecognizeResult = 10;</code>
     * @return The bytes for originalRecognizeResult.
     */
    com.google.protobuf.ByteString
        getOriginalRecognizeResultBytes();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportWrongAnswerReq}
   */
  public  static final class ReportWrongAnswerReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.ReportWrongAnswerReq)
      ReportWrongAnswerReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReportWrongAnswerReq.newBuilder() to construct.
    private ReportWrongAnswerReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReportWrongAnswerReq() {
      shownAnswer_ = "";
      recordFileName_ = "";
      recordFileContent_ = com.google.protobuf.ByteString.EMPTY;
      originalRecognizeResult_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReportWrongAnswerReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReportWrongAnswerReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numberToRead_ = input.readUInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              shownAnswer_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              recordFileName_ = s;
              break;
            }
            case 34: {

              recordFileContent_ = input.readBytes();
              break;
            }
            case 42: {
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder subBuilder = null;
              if (photoFile_ != null) {
                subBuilder = photoFile_.toBuilder();
              }
              photoFile_ = input.readMessage(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(photoFile_);
                photoFile_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder subBuilder = null;
              if (recordFile_ != null) {
                subBuilder = recordFile_.toBuilder();
              }
              recordFile_ = input.readMessage(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(recordFile_);
                recordFile_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              originalRecognizeResult_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.class, com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.Builder.class);
    }

    public static final int NUMBERTOREAD_FIELD_NUMBER = 1;
    private int numberToRead_;
    /**
     * <pre>
     *!&lt;要读出的数字。
     * </pre>
     *
     * <code>uint32 numberToRead = 1;</code>
     * @return The numberToRead.
     */
    public int getNumberToRead() {
      return numberToRead_;
    }

    public static final int SHOWNANSWER_FIELD_NUMBER = 2;
    private volatile java.lang.Object shownAnswer_;
    /**
     * <pre>
     *!&lt;当前显示的答案
     * </pre>
     *
     * <code>string shownAnswer = 2;</code>
     * @return The shownAnswer.
     */
    public java.lang.String getShownAnswer() {
      java.lang.Object ref = shownAnswer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shownAnswer_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *!&lt;当前显示的答案
     * </pre>
     *
     * <code>string shownAnswer = 2;</code>
     * @return The bytes for shownAnswer.
     */
    public com.google.protobuf.ByteString
        getShownAnswerBytes() {
      java.lang.Object ref = shownAnswer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shownAnswer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDFILENAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object recordFileName_;
    /**
     * <pre>
     *!&lt;录音文件名。
     * </pre>
     *
     * <code>string recordFileName = 3;</code>
     * @return The recordFileName.
     */
    public java.lang.String getRecordFileName() {
      java.lang.Object ref = recordFileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordFileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *!&lt;录音文件名。
     * </pre>
     *
     * <code>string recordFileName = 3;</code>
     * @return The bytes for recordFileName.
     */
    public com.google.protobuf.ByteString
        getRecordFileNameBytes() {
      java.lang.Object ref = recordFileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDFILECONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString recordFileContent_;
    /**
     * <pre>
     *!&lt;录音文件内容。
     * </pre>
     *
     * <code>bytes recordFileContent = 4;</code>
     * @return The recordFileContent.
     */
    public com.google.protobuf.ByteString getRecordFileContent() {
      return recordFileContent_;
    }

    public static final int PHOTOFILE_FIELD_NUMBER = 5;
    private com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage photoFile_;
    /**
     * <pre>
     *!&lt;照片文件。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
     * @return Whether the photoFile field is set.
     */
    public boolean hasPhotoFile() {
      return photoFile_ != null;
    }
    /**
     * <pre>
     *!&lt;照片文件。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
     * @return The photoFile.
     */
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getPhotoFile() {
      return photoFile_ == null ? com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance() : photoFile_;
    }
    /**
     * <pre>
     *!&lt;照片文件。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
     */
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getPhotoFileOrBuilder() {
      return getPhotoFile();
    }

    public static final int RECORDFILE_FIELD_NUMBER = 6;
    private com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage recordFile_;
    /**
     * <pre>
     *!&lt;录音文件。替代 录音文件名 和 录音文件内容
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
     * @return Whether the recordFile field is set.
     */
    public boolean hasRecordFile() {
      return recordFile_ != null;
    }
    /**
     * <pre>
     *!&lt;录音文件。替代 录音文件名 和 录音文件内容
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
     * @return The recordFile.
     */
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getRecordFile() {
      return recordFile_ == null ? com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance() : recordFile_;
    }
    /**
     * <pre>
     *!&lt;录音文件。替代 录音文件名 和 录音文件内容
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
     */
    public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getRecordFileOrBuilder() {
      return getRecordFile();
    }

    public static final int ORIGINALRECOGNIZERESULT_FIELD_NUMBER = 10;
    private volatile java.lang.Object originalRecognizeResult_;
    /**
     * <pre>
     *!&lt;原始识别结果。
     * </pre>
     *
     * <code>string originalRecognizeResult = 10;</code>
     * @return The originalRecognizeResult.
     */
    public java.lang.String getOriginalRecognizeResult() {
      java.lang.Object ref = originalRecognizeResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalRecognizeResult_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *!&lt;原始识别结果。
     * </pre>
     *
     * <code>string originalRecognizeResult = 10;</code>
     * @return The bytes for originalRecognizeResult.
     */
    public com.google.protobuf.ByteString
        getOriginalRecognizeResultBytes() {
      java.lang.Object ref = originalRecognizeResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalRecognizeResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numberToRead_ != 0) {
        output.writeUInt32(1, numberToRead_);
      }
      if (!getShownAnswerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, shownAnswer_);
      }
      if (!getRecordFileNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, recordFileName_);
      }
      if (!recordFileContent_.isEmpty()) {
        output.writeBytes(4, recordFileContent_);
      }
      if (photoFile_ != null) {
        output.writeMessage(5, getPhotoFile());
      }
      if (recordFile_ != null) {
        output.writeMessage(6, getRecordFile());
      }
      if (!getOriginalRecognizeResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, originalRecognizeResult_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numberToRead_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, numberToRead_);
      }
      if (!getShownAnswerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, shownAnswer_);
      }
      if (!getRecordFileNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, recordFileName_);
      }
      if (!recordFileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, recordFileContent_);
      }
      if (photoFile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPhotoFile());
      }
      if (recordFile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getRecordFile());
      }
      if (!getOriginalRecognizeResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, originalRecognizeResult_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq other = (com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq) obj;

      if (getNumberToRead()
          != other.getNumberToRead()) return false;
      if (!getShownAnswer()
          .equals(other.getShownAnswer())) return false;
      if (!getRecordFileName()
          .equals(other.getRecordFileName())) return false;
      if (!getRecordFileContent()
          .equals(other.getRecordFileContent())) return false;
      if (hasPhotoFile() != other.hasPhotoFile()) return false;
      if (hasPhotoFile()) {
        if (!getPhotoFile()
            .equals(other.getPhotoFile())) return false;
      }
      if (hasRecordFile() != other.hasRecordFile()) return false;
      if (hasRecordFile()) {
        if (!getRecordFile()
            .equals(other.getRecordFile())) return false;
      }
      if (!getOriginalRecognizeResult()
          .equals(other.getOriginalRecognizeResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBERTOREAD_FIELD_NUMBER;
      hash = (53 * hash) + getNumberToRead();
      hash = (37 * hash) + SHOWNANSWER_FIELD_NUMBER;
      hash = (53 * hash) + getShownAnswer().hashCode();
      hash = (37 * hash) + RECORDFILENAME_FIELD_NUMBER;
      hash = (53 * hash) + getRecordFileName().hashCode();
      hash = (37 * hash) + RECORDFILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getRecordFileContent().hashCode();
      if (hasPhotoFile()) {
        hash = (37 * hash) + PHOTOFILE_FIELD_NUMBER;
        hash = (53 * hash) + getPhotoFile().hashCode();
      }
      if (hasRecordFile()) {
        hash = (37 * hash) + RECORDFILE_FIELD_NUMBER;
        hash = (53 * hash) + getRecordFile().hashCode();
      }
      hash = (37 * hash) + ORIGINALRECOGNIZERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalRecognizeResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportWrongAnswerReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.ReportWrongAnswerReq)
        com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.class, com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numberToRead_ = 0;

        shownAnswer_ = "";

        recordFileName_ = "";

        recordFileContent_ = com.google.protobuf.ByteString.EMPTY;

        if (photoFileBuilder_ == null) {
          photoFile_ = null;
        } else {
          photoFile_ = null;
          photoFileBuilder_ = null;
        }
        if (recordFileBuilder_ == null) {
          recordFile_ = null;
        } else {
          recordFile_ = null;
          recordFileBuilder_ = null;
        }
        originalRecognizeResult_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq build() {
        com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq buildPartial() {
        com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq result = new com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq(this);
        result.numberToRead_ = numberToRead_;
        result.shownAnswer_ = shownAnswer_;
        result.recordFileName_ = recordFileName_;
        result.recordFileContent_ = recordFileContent_;
        if (photoFileBuilder_ == null) {
          result.photoFile_ = photoFile_;
        } else {
          result.photoFile_ = photoFileBuilder_.build();
        }
        if (recordFileBuilder_ == null) {
          result.recordFile_ = recordFile_;
        } else {
          result.recordFile_ = recordFileBuilder_.build();
        }
        result.originalRecognizeResult_ = originalRecognizeResult_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq) {
          return mergeFrom((com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq other) {
        if (other == com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq.getDefaultInstance()) return this;
        if (other.getNumberToRead() != 0) {
          setNumberToRead(other.getNumberToRead());
        }
        if (!other.getShownAnswer().isEmpty()) {
          shownAnswer_ = other.shownAnswer_;
          onChanged();
        }
        if (!other.getRecordFileName().isEmpty()) {
          recordFileName_ = other.recordFileName_;
          onChanged();
        }
        if (other.getRecordFileContent() != com.google.protobuf.ByteString.EMPTY) {
          setRecordFileContent(other.getRecordFileContent());
        }
        if (other.hasPhotoFile()) {
          mergePhotoFile(other.getPhotoFile());
        }
        if (other.hasRecordFile()) {
          mergeRecordFile(other.getRecordFile());
        }
        if (!other.getOriginalRecognizeResult().isEmpty()) {
          originalRecognizeResult_ = other.originalRecognizeResult_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numberToRead_ ;
      /**
       * <pre>
       *!&lt;要读出的数字。
       * </pre>
       *
       * <code>uint32 numberToRead = 1;</code>
       * @return The numberToRead.
       */
      public int getNumberToRead() {
        return numberToRead_;
      }
      /**
       * <pre>
       *!&lt;要读出的数字。
       * </pre>
       *
       * <code>uint32 numberToRead = 1;</code>
       * @param value The numberToRead to set.
       * @return This builder for chaining.
       */
      public Builder setNumberToRead(int value) {
        
        numberToRead_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;要读出的数字。
       * </pre>
       *
       * <code>uint32 numberToRead = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberToRead() {
        
        numberToRead_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object shownAnswer_ = "";
      /**
       * <pre>
       *!&lt;当前显示的答案
       * </pre>
       *
       * <code>string shownAnswer = 2;</code>
       * @return The shownAnswer.
       */
      public java.lang.String getShownAnswer() {
        java.lang.Object ref = shownAnswer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shownAnswer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *!&lt;当前显示的答案
       * </pre>
       *
       * <code>string shownAnswer = 2;</code>
       * @return The bytes for shownAnswer.
       */
      public com.google.protobuf.ByteString
          getShownAnswerBytes() {
        java.lang.Object ref = shownAnswer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shownAnswer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *!&lt;当前显示的答案
       * </pre>
       *
       * <code>string shownAnswer = 2;</code>
       * @param value The shownAnswer to set.
       * @return This builder for chaining.
       */
      public Builder setShownAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shownAnswer_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;当前显示的答案
       * </pre>
       *
       * <code>string shownAnswer = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearShownAnswer() {
        
        shownAnswer_ = getDefaultInstance().getShownAnswer();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;当前显示的答案
       * </pre>
       *
       * <code>string shownAnswer = 2;</code>
       * @param value The bytes for shownAnswer to set.
       * @return This builder for chaining.
       */
      public Builder setShownAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shownAnswer_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordFileName_ = "";
      /**
       * <pre>
       *!&lt;录音文件名。
       * </pre>
       *
       * <code>string recordFileName = 3;</code>
       * @return The recordFileName.
       */
      public java.lang.String getRecordFileName() {
        java.lang.Object ref = recordFileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordFileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *!&lt;录音文件名。
       * </pre>
       *
       * <code>string recordFileName = 3;</code>
       * @return The bytes for recordFileName.
       */
      public com.google.protobuf.ByteString
          getRecordFileNameBytes() {
        java.lang.Object ref = recordFileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordFileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *!&lt;录音文件名。
       * </pre>
       *
       * <code>string recordFileName = 3;</code>
       * @param value The recordFileName to set.
       * @return This builder for chaining.
       */
      public Builder setRecordFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordFileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件名。
       * </pre>
       *
       * <code>string recordFileName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecordFileName() {
        
        recordFileName_ = getDefaultInstance().getRecordFileName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件名。
       * </pre>
       *
       * <code>string recordFileName = 3;</code>
       * @param value The bytes for recordFileName to set.
       * @return This builder for chaining.
       */
      public Builder setRecordFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordFileName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString recordFileContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *!&lt;录音文件内容。
       * </pre>
       *
       * <code>bytes recordFileContent = 4;</code>
       * @return The recordFileContent.
       */
      public com.google.protobuf.ByteString getRecordFileContent() {
        return recordFileContent_;
      }
      /**
       * <pre>
       *!&lt;录音文件内容。
       * </pre>
       *
       * <code>bytes recordFileContent = 4;</code>
       * @param value The recordFileContent to set.
       * @return This builder for chaining.
       */
      public Builder setRecordFileContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordFileContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件内容。
       * </pre>
       *
       * <code>bytes recordFileContent = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecordFileContent() {
        
        recordFileContent_ = getDefaultInstance().getRecordFileContent();
        onChanged();
        return this;
      }

      private com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage photoFile_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> photoFileBuilder_;
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       * @return Whether the photoFile field is set.
       */
      public boolean hasPhotoFile() {
        return photoFileBuilder_ != null || photoFile_ != null;
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       * @return The photoFile.
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getPhotoFile() {
        if (photoFileBuilder_ == null) {
          return photoFile_ == null ? com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance() : photoFile_;
        } else {
          return photoFileBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      public Builder setPhotoFile(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (photoFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          photoFile_ = value;
          onChanged();
        } else {
          photoFileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      public Builder setPhotoFile(
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (photoFileBuilder_ == null) {
          photoFile_ = builderForValue.build();
          onChanged();
        } else {
          photoFileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      public Builder mergePhotoFile(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (photoFileBuilder_ == null) {
          if (photoFile_ != null) {
            photoFile_ =
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.newBuilder(photoFile_).mergeFrom(value).buildPartial();
          } else {
            photoFile_ = value;
          }
          onChanged();
        } else {
          photoFileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      public Builder clearPhotoFile() {
        if (photoFileBuilder_ == null) {
          photoFile_ = null;
          onChanged();
        } else {
          photoFile_ = null;
          photoFileBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder getPhotoFileBuilder() {
        
        onChanged();
        return getPhotoFileFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getPhotoFileOrBuilder() {
        if (photoFileBuilder_ != null) {
          return photoFileBuilder_.getMessageOrBuilder();
        } else {
          return photoFile_ == null ?
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance() : photoFile_;
        }
      }
      /**
       * <pre>
       *!&lt;照片文件。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage photoFile = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> 
          getPhotoFileFieldBuilder() {
        if (photoFileBuilder_ == null) {
          photoFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder>(
                  getPhotoFile(),
                  getParentForChildren(),
                  isClean());
          photoFile_ = null;
        }
        return photoFileBuilder_;
      }

      private com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage recordFile_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> recordFileBuilder_;
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       * @return Whether the recordFile field is set.
       */
      public boolean hasRecordFile() {
        return recordFileBuilder_ != null || recordFile_ != null;
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       * @return The recordFile.
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage getRecordFile() {
        if (recordFileBuilder_ == null) {
          return recordFile_ == null ? com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance() : recordFile_;
        } else {
          return recordFileBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      public Builder setRecordFile(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (recordFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          recordFile_ = value;
          onChanged();
        } else {
          recordFileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      public Builder setRecordFile(
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder builderForValue) {
        if (recordFileBuilder_ == null) {
          recordFile_ = builderForValue.build();
          onChanged();
        } else {
          recordFileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      public Builder mergeRecordFile(com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage value) {
        if (recordFileBuilder_ == null) {
          if (recordFile_ != null) {
            recordFile_ =
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.newBuilder(recordFile_).mergeFrom(value).buildPartial();
          } else {
            recordFile_ = value;
          }
          onChanged();
        } else {
          recordFileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      public Builder clearRecordFile() {
        if (recordFileBuilder_ == null) {
          recordFile_ = null;
          onChanged();
        } else {
          recordFile_ = null;
          recordFileBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder getRecordFileBuilder() {
        
        onChanged();
        return getRecordFileFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      public com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder getRecordFileOrBuilder() {
        if (recordFileBuilder_ != null) {
          return recordFileBuilder_.getMessageOrBuilder();
        } else {
          return recordFile_ == null ?
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.getDefaultInstance() : recordFile_;
        }
      }
      /**
       * <pre>
       *!&lt;录音文件。替代 录音文件名 和 录音文件内容
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.FileMessage recordFile = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder> 
          getRecordFileFieldBuilder() {
        if (recordFileBuilder_ == null) {
          recordFileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessage.Builder, com.stupidbeauty.hxlauncher.FileMessageOuterClass.FileMessageOrBuilder>(
                  getRecordFile(),
                  getParentForChildren(),
                  isClean());
          recordFile_ = null;
        }
        return recordFileBuilder_;
      }

      private java.lang.Object originalRecognizeResult_ = "";
      /**
       * <pre>
       *!&lt;原始识别结果。
       * </pre>
       *
       * <code>string originalRecognizeResult = 10;</code>
       * @return The originalRecognizeResult.
       */
      public java.lang.String getOriginalRecognizeResult() {
        java.lang.Object ref = originalRecognizeResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          originalRecognizeResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *!&lt;原始识别结果。
       * </pre>
       *
       * <code>string originalRecognizeResult = 10;</code>
       * @return The bytes for originalRecognizeResult.
       */
      public com.google.protobuf.ByteString
          getOriginalRecognizeResultBytes() {
        java.lang.Object ref = originalRecognizeResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          originalRecognizeResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *!&lt;原始识别结果。
       * </pre>
       *
       * <code>string originalRecognizeResult = 10;</code>
       * @param value The originalRecognizeResult to set.
       * @return This builder for chaining.
       */
      public Builder setOriginalRecognizeResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        originalRecognizeResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;原始识别结果。
       * </pre>
       *
       * <code>string originalRecognizeResult = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginalRecognizeResult() {
        
        originalRecognizeResult_ = getDefaultInstance().getOriginalRecognizeResult();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;原始识别结果。
       * </pre>
       *
       * <code>string originalRecognizeResult = 10;</code>
       * @param value The bytes for originalRecognizeResult to set.
       * @return This builder for chaining.
       */
      public Builder setOriginalRecognizeResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        originalRecognizeResult_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.ReportWrongAnswerReq)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.ReportWrongAnswerReq)
    private static final com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq();
    }

    public static com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReportWrongAnswerReq>
        PARSER = new com.google.protobuf.AbstractParser<ReportWrongAnswerReq>() {
      @java.lang.Override
      public ReportWrongAnswerReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReportWrongAnswerReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReportWrongAnswerReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReportWrongAnswerReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportWrongAnswerReqOuterClass.ReportWrongAnswerReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032ReportWrongAnswerReq.proto\022\033com.stupid" +
      "beauty.hxlauncher\032\021FileMessage.proto\"\220\002\n" +
      "\024ReportWrongAnswerReq\022\024\n\014numberToRead\030\001 " +
      "\001(\r\022\023\n\013shownAnswer\030\002 \001(\t\022\026\n\016recordFileNa" +
      "me\030\003 \001(\t\022\031\n\021recordFileContent\030\004 \001(\014\022;\n\tp" +
      "hotoFile\030\005 \001(\0132(.com.stupidbeauty.hxlaun" +
      "cher.FileMessage\022<\n\nrecordFile\030\006 \001(\0132(.c" +
      "om.stupidbeauty.hxlauncher.FileMessage\022\037" +
      "\n\027originalRecognizeResult\030\n \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.FileMessageOuterClass.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReportWrongAnswerReq_descriptor,
        new java.lang.String[] { "NumberToRead", "ShownAnswer", "RecordFileName", "RecordFileContent", "PhotoFile", "RecordFile", "OriginalRecognizeResult", });
    com.stupidbeauty.hxlauncher.FileMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
