// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpeakerSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public interface SpeakerSubSystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *简体中文的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngine = 1;</code>
   * @return The ttsEngine.
   */
  java.lang.String getTtsEngine();
  /**
   * <pre>
   *简体中文的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngine = 1;</code>
   * @return The bytes for ttsEngine.
   */
  com.google.protobuf.ByteString
      getTtsEngineBytes();

  /**
   * <pre>
   *广东话的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineYueHantHk = 2;</code>
   * @return The ttsEngineYueHantHk.
   */
  java.lang.String getTtsEngineYueHantHk();
  /**
   * <pre>
   *广东话的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineYueHantHk = 2;</code>
   * @return The bytes for ttsEngineYueHantHk.
   */
  com.google.protobuf.ByteString
      getTtsEngineYueHantHkBytes();

  /**
   * <pre>
   *英语的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineEnUs = 3;</code>
   * @return The ttsEngineEnUs.
   */
  java.lang.String getTtsEngineEnUs();
  /**
   * <pre>
   *英语的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineEnUs = 3;</code>
   * @return The bytes for ttsEngineEnUs.
   */
  com.google.protobuf.ByteString
      getTtsEngineEnUsBytes();

  /**
   * <pre>
   *Nuance语音合成的引擎地址。
   * </pre>
   *
   * <code>string xiaoINuanceServiceUrl = 4;</code>
   * @return The xiaoINuanceServiceUrl.
   */
  java.lang.String getXiaoINuanceServiceUrl();
  /**
   * <pre>
   *Nuance语音合成的引擎地址。
   * </pre>
   *
   * <code>string xiaoINuanceServiceUrl = 4;</code>
   * @return The bytes for xiaoINuanceServiceUrl.
   */
  com.google.protobuf.ByteString
      getXiaoINuanceServiceUrlBytes();

  /**
   * <pre>
   *标贝语音合成的服务地址。
   * </pre>
   *
   * <code>string biaobeiServiceUrl = 5;</code>
   * @return The biaobeiServiceUrl.
   */
  java.lang.String getBiaobeiServiceUrl();
  /**
   * <pre>
   *标贝语音合成的服务地址。
   * </pre>
   *
   * <code>string biaobeiServiceUrl = 5;</code>
   * @return The bytes for biaobeiServiceUrl.
   */
  com.google.protobuf.ByteString
      getBiaobeiServiceUrlBytes();

  /**
   * <pre>
   *标贝语音合成的用户编号。
   * </pre>
   *
   * <code>string biaobeiServiceUserId = 6;</code>
   * @return The biaobeiServiceUserId.
   */
  java.lang.String getBiaobeiServiceUserId();
  /**
   * <pre>
   *标贝语音合成的用户编号。
   * </pre>
   *
   * <code>string biaobeiServiceUserId = 6;</code>
   * @return The bytes for biaobeiServiceUserId.
   */
  com.google.protobuf.ByteString
      getBiaobeiServiceUserIdBytes();

  /**
   * <pre>
   *设置三维人像的背景图片。
   * </pre>
   *
   * <code>string xunfeiSdkAppId = 7;</code>
   * @return The xunfeiSdkAppId.
   */
  java.lang.String getXunfeiSdkAppId();
  /**
   * <pre>
   *设置三维人像的背景图片。
   * </pre>
   *
   * <code>string xunfeiSdkAppId = 7;</code>
   * @return The bytes for xunfeiSdkAppId.
   */
  com.google.protobuf.ByteString
      getXunfeiSdkAppIdBytes();

  /**
   * <pre>
   *讯飞语音合成的SO文件的目录。
   * </pre>
   *
   * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
   * @return The xunfeiSdkLibMscSoDirectory.
   */
  java.lang.String getXunfeiSdkLibMscSoDirectory();
  /**
   * <pre>
   *讯飞语音合成的SO文件的目录。
   * </pre>
   *
   * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
   * @return The bytes for xunfeiSdkLibMscSoDirectory.
   */
  com.google.protobuf.ByteString
      getXunfeiSdkLibMscSoDirectoryBytes();

  /**
   * <pre>
   *SPPAS模块的IP。
   * </pre>
   *
   * <code>string sppasToolsIp = 9;</code>
   * @return The sppasToolsIp.
   */
  java.lang.String getSppasToolsIp();
  /**
   * <pre>
   *SPPAS模块的IP。
   * </pre>
   *
   * <code>string sppasToolsIp = 9;</code>
   * @return The bytes for sppasToolsIp.
   */
  com.google.protobuf.ByteString
      getSppasToolsIpBytes();

  /**
   * <pre>
   *声音缓存文件目录。
   * </pre>
   *
   * <code>string cacheDirectory = 10;</code>
   * @return The cacheDirectory.
   */
  java.lang.String getCacheDirectory();
  /**
   * <pre>
   *声音缓存文件目录。
   * </pre>
   *
   * <code>string cacheDirectory = 10;</code>
   * @return The bytes for cacheDirectory.
   */
  com.google.protobuf.ByteString
      getCacheDirectoryBytes();

  /**
   * <pre>
   *语速。
   * </pre>
   *
   * <code>int32 speed = 11;</code>
   * @return The speed.
   */
  int getSpeed();

  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return Whether the reportAccurateVoiceCommandMessage field is set.
   */
  boolean hasReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return The reportAccurateVoiceCommandMessage.
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq getReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder getReportAccurateVoiceCommandMessageOrBuilder();

  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return Whether the reportVoiceRecognizedMessage field is set.
   */
  boolean hasReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return The reportVoiceRecognizedMessage.
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder();
}
