// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubSystemProcessLocationMessage.proto

package com.stupidbeauty.hxlauncher;

public final class SubSystemProcessLocationMessageProtos {
  private SubSystemProcessLocationMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_SubSystemProcessLocationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_SubSystemProcessLocationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%SubSystemProcessLocationMessage.proto\022" +
      "\033com.stupidbeauty.hxlauncher\032\037ReportAudi" +
      "oSoundSourceReq.proto\032\035AccurateVoiceComm" +
      "andReq.proto\032\036ReportVoiceRecognizedReq.p" +
      "roto\"\202\003\n\037SubSystemProcessLocationMessage" +
      "\022\016\n\006camera\030\001 \001(\t\022\027\n\017humanBodyDetect\030\002 \001(" +
      "\t\022\026\n\016iBotEx3DEngine\030\003 \001(\t\022`\n reportAudio" +
      "SoundSourceReqMessage\030\006 \001(\01326.com.stupid" +
      "beauty.hxlauncher.ReportAudioSoundSource" +
      "Req\022_\n!reportAccurateVoiceCommandMessage" +
      "\030\023 \001(\01324.com.stupidbeauty.hxlauncher.Acc" +
      "urateVoiceCommandReq\022[\n\034reportVoiceRecog" +
      "nizedMessage\030\024 \001(\01325.com.stupidbeauty.hx" +
      "launcher.ReportVoiceRecognizedReqBF\n\033com" +
      ".stupidbeauty.hxlauncherB%SubSystemProce" +
      "ssLocationMessageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_SubSystemProcessLocationMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_SubSystemProcessLocationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_SubSystemProcessLocationMessage_descriptor,
        new java.lang.String[] { "Camera", "HumanBodyDetect", "IBotEx3DEngine", "ReportAudioSoundSourceReqMessage", "ReportAccurateVoiceCommandMessage", "ReportVoiceRecognizedMessage", });
    com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
