// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubSystemProcessLocationMessage.proto

package com.stupidbeauty.hxlauncher;

public interface SubSystemProcessLocationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.SubSystemProcessLocationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *摄像头子系统的进程位置。
   * </pre>
   *
   * <code>string camera = 1;</code>
   * @return The camera.
   */
  java.lang.String getCamera();
  /**
   * <pre>
   *摄像头子系统的进程位置。
   * </pre>
   *
   * <code>string camera = 1;</code>
   * @return The bytes for camera.
   */
  com.google.protobuf.ByteString
      getCameraBytes();

  /**
   * <pre>
   *人体检测模块的进程位置。
   * </pre>
   *
   * <code>string humanBodyDetect = 2;</code>
   * @return The humanBodyDetect.
   */
  java.lang.String getHumanBodyDetect();
  /**
   * <pre>
   *人体检测模块的进程位置。
   * </pre>
   *
   * <code>string humanBodyDetect = 2;</code>
   * @return The bytes for humanBodyDetect.
   */
  com.google.protobuf.ByteString
      getHumanBodyDetectBytes();

  /**
   * <pre>
   *三维人像引擎的进程位置。
   * </pre>
   *
   * <code>string iBotEx3DEngine = 3;</code>
   * @return The iBotEx3DEngine.
   */
  java.lang.String getIBotEx3DEngine();
  /**
   * <pre>
   *三维人像引擎的进程位置。
   * </pre>
   *
   * <code>string iBotEx3DEngine = 3;</code>
   * @return The bytes for iBotEx3DEngine.
   */
  com.google.protobuf.ByteString
      getIBotEx3DEngineBytes();

  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return Whether the reportAudioSoundSourceReqMessage field is set.
   */
  boolean hasReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return The reportAudioSoundSourceReqMessage.
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder();

  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return Whether the reportAccurateVoiceCommandMessage field is set.
   */
  boolean hasReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return The reportAccurateVoiceCommandMessage.
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq getReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder getReportAccurateVoiceCommandMessageOrBuilder();

  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return Whether the reportVoiceRecognizedMessage field is set.
   */
  boolean hasReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return The reportVoiceRecognizedMessage.
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder();
}
