// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTSEngineParameterMessage.proto

package com.stupidbeauty.hxlauncher;

public interface TTSEngineParameterMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *参数类型。
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   *参数类型。
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   *语速。
   * </pre>
   *
   * <code>int32 speed = 2;</code>
   * @return The speed.
   */
  int getSpeed();

  /**
   * <pre>
   *音量。
   * </pre>
   *
   * <code>int32 volume = 3;</code>
   * @return The volume.
   */
  int getVolume();

  /**
   * <pre>
   *语速。
   * </pre>
   *
   * <code>int32 spd = 4;</code>
   * @return The spd.
   */
  int getSpd();

  /**
   * <pre>
   *音调。
   * </pre>
   *
   * <code>int32 pit = 5;</code>
   * @return The pit.
   */
  int getPit();

  /**
   * <pre>
   *音量。
   * </pre>
   *
   * <code>int32 vol = 6;</code>
   * @return The vol.
   */
  int getVol();
}
