// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTSEngineParameterMessage.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.TTSEngineParameterMessage}
 */
public  final class TTSEngineParameterMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)
    TTSEngineParameterMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TTSEngineParameterMessage.newBuilder() to construct.
  private TTSEngineParameterMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TTSEngineParameterMessage() {
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TTSEngineParameterMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TTSEngineParameterMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 16: {

            speed_ = input.readInt32();
            break;
          }
          case 24: {

            volume_ = input.readInt32();
            break;
          }
          case 32: {

            spd_ = input.readInt32();
            break;
          }
          case 40: {

            pit_ = input.readInt32();
            break;
          }
          case 48: {

            vol_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.TTSEngineParameterMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineParameterMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.TTSEngineParameterMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineParameterMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.class, com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   *参数类型。
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *参数类型。
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPEED_FIELD_NUMBER = 2;
  private int speed_;
  /**
   * <pre>
   *语速。
   * </pre>
   *
   * <code>int32 speed = 2;</code>
   * @return The speed.
   */
  public int getSpeed() {
    return speed_;
  }

  public static final int VOLUME_FIELD_NUMBER = 3;
  private int volume_;
  /**
   * <pre>
   *音量。
   * </pre>
   *
   * <code>int32 volume = 3;</code>
   * @return The volume.
   */
  public int getVolume() {
    return volume_;
  }

  public static final int SPD_FIELD_NUMBER = 4;
  private int spd_;
  /**
   * <pre>
   *语速。
   * </pre>
   *
   * <code>int32 spd = 4;</code>
   * @return The spd.
   */
  public int getSpd() {
    return spd_;
  }

  public static final int PIT_FIELD_NUMBER = 5;
  private int pit_;
  /**
   * <pre>
   *音调。
   * </pre>
   *
   * <code>int32 pit = 5;</code>
   * @return The pit.
   */
  public int getPit() {
    return pit_;
  }

  public static final int VOL_FIELD_NUMBER = 6;
  private int vol_;
  /**
   * <pre>
   *音量。
   * </pre>
   *
   * <code>int32 vol = 6;</code>
   * @return The vol.
   */
  public int getVol() {
    return vol_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (speed_ != 0) {
      output.writeInt32(2, speed_);
    }
    if (volume_ != 0) {
      output.writeInt32(3, volume_);
    }
    if (spd_ != 0) {
      output.writeInt32(4, spd_);
    }
    if (pit_ != 0) {
      output.writeInt32(5, pit_);
    }
    if (vol_ != 0) {
      output.writeInt32(6, vol_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (speed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, speed_);
    }
    if (volume_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, volume_);
    }
    if (spd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, spd_);
    }
    if (pit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, pit_);
    }
    if (vol_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, vol_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.TTSEngineParameterMessage other = (com.stupidbeauty.hxlauncher.TTSEngineParameterMessage) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (getSpeed()
        != other.getSpeed()) return false;
    if (getVolume()
        != other.getVolume()) return false;
    if (getSpd()
        != other.getSpd()) return false;
    if (getPit()
        != other.getPit()) return false;
    if (getVol()
        != other.getVol()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + getSpeed();
    hash = (37 * hash) + VOLUME_FIELD_NUMBER;
    hash = (53 * hash) + getVolume();
    hash = (37 * hash) + SPD_FIELD_NUMBER;
    hash = (53 * hash) + getSpd();
    hash = (37 * hash) + PIT_FIELD_NUMBER;
    hash = (53 * hash) + getPit();
    hash = (37 * hash) + VOL_FIELD_NUMBER;
    hash = (53 * hash) + getVol();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.TTSEngineParameterMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.TTSEngineParameterMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)
      com.stupidbeauty.hxlauncher.TTSEngineParameterMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.TTSEngineParameterMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineParameterMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.TTSEngineParameterMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineParameterMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.class, com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      speed_ = 0;

      volume_ = 0;

      spd_ = 0;

      pit_ = 0;

      vol_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.TTSEngineParameterMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineParameterMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage build() {
      com.stupidbeauty.hxlauncher.TTSEngineParameterMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage buildPartial() {
      com.stupidbeauty.hxlauncher.TTSEngineParameterMessage result = new com.stupidbeauty.hxlauncher.TTSEngineParameterMessage(this);
      result.type_ = type_;
      result.speed_ = speed_;
      result.volume_ = volume_;
      result.spd_ = spd_;
      result.pit_ = pit_;
      result.vol_ = vol_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.TTSEngineParameterMessage) {
        return mergeFrom((com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.TTSEngineParameterMessage other) {
      if (other == com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getSpeed() != 0) {
        setSpeed(other.getSpeed());
      }
      if (other.getVolume() != 0) {
        setVolume(other.getVolume());
      }
      if (other.getSpd() != 0) {
        setSpd(other.getSpd());
      }
      if (other.getPit() != 0) {
        setPit(other.getPit());
      }
      if (other.getVol() != 0) {
        setVol(other.getVol());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.TTSEngineParameterMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.TTSEngineParameterMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     *参数类型。
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *参数类型。
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *参数类型。
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数类型。
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *参数类型。
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int speed_ ;
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 speed = 2;</code>
     * @return The speed.
     */
    public int getSpeed() {
      return speed_;
    }
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 speed = 2;</code>
     * @param value The speed to set.
     * @return This builder for chaining.
     */
    public Builder setSpeed(int value) {
      
      speed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 speed = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpeed() {
      
      speed_ = 0;
      onChanged();
      return this;
    }

    private int volume_ ;
    /**
     * <pre>
     *音量。
     * </pre>
     *
     * <code>int32 volume = 3;</code>
     * @return The volume.
     */
    public int getVolume() {
      return volume_;
    }
    /**
     * <pre>
     *音量。
     * </pre>
     *
     * <code>int32 volume = 3;</code>
     * @param value The volume to set.
     * @return This builder for chaining.
     */
    public Builder setVolume(int value) {
      
      volume_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *音量。
     * </pre>
     *
     * <code>int32 volume = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVolume() {
      
      volume_ = 0;
      onChanged();
      return this;
    }

    private int spd_ ;
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 spd = 4;</code>
     * @return The spd.
     */
    public int getSpd() {
      return spd_;
    }
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 spd = 4;</code>
     * @param value The spd to set.
     * @return This builder for chaining.
     */
    public Builder setSpd(int value) {
      
      spd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 spd = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpd() {
      
      spd_ = 0;
      onChanged();
      return this;
    }

    private int pit_ ;
    /**
     * <pre>
     *音调。
     * </pre>
     *
     * <code>int32 pit = 5;</code>
     * @return The pit.
     */
    public int getPit() {
      return pit_;
    }
    /**
     * <pre>
     *音调。
     * </pre>
     *
     * <code>int32 pit = 5;</code>
     * @param value The pit to set.
     * @return This builder for chaining.
     */
    public Builder setPit(int value) {
      
      pit_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *音调。
     * </pre>
     *
     * <code>int32 pit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPit() {
      
      pit_ = 0;
      onChanged();
      return this;
    }

    private int vol_ ;
    /**
     * <pre>
     *音量。
     * </pre>
     *
     * <code>int32 vol = 6;</code>
     * @return The vol.
     */
    public int getVol() {
      return vol_;
    }
    /**
     * <pre>
     *音量。
     * </pre>
     *
     * <code>int32 vol = 6;</code>
     * @param value The vol to set.
     * @return This builder for chaining.
     */
    public Builder setVol(int value) {
      
      vol_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *音量。
     * </pre>
     *
     * <code>int32 vol = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVol() {
      
      vol_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.TTSEngineParameterMessage)
  private static final com.stupidbeauty.hxlauncher.TTSEngineParameterMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.TTSEngineParameterMessage();
  }

  public static com.stupidbeauty.hxlauncher.TTSEngineParameterMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TTSEngineParameterMessage>
      PARSER = new com.google.protobuf.AbstractParser<TTSEngineParameterMessage>() {
    @java.lang.Override
    public TTSEngineParameterMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TTSEngineParameterMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TTSEngineParameterMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TTSEngineParameterMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

