// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceCommandHitDataMessage.proto

package com.stupidbeauty.hxlauncher;

public final class VoiceCommandHitDataMessageProtos {
  private VoiceCommandHitDataMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VoiceCommandHitDataMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The voiceRecognizeResult.
     */
    java.lang.String getVoiceRecognizeResult();
    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The bytes for voiceRecognizeResult.
     */
    com.google.protobuf.ByteString
        getVoiceRecognizeResultBytes();

    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The packageName.
     */
    java.lang.String getPackageName();
    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The bytes for packageName.
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <pre>
     *录音文件内容。
     * </pre>
     *
     * <code>bytes asrWavFileContent = 3;</code>
     * @return The asrWavFileContent.
     */
    com.google.protobuf.ByteString getAsrWavFileContent();

    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The activityName.
     */
    java.lang.String getActivityName();
    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The bytes for activityName.
     */
    com.google.protobuf.ByteString
        getActivityNameBytes();

    /**
     * <pre>
     *图标标题。
     * </pre>
     *
     * <code>string iconTitle = 5;</code>
     * @return The iconTitle.
     */
    java.lang.String getIconTitle();
    /**
     * <pre>
     *图标标题。
     * </pre>
     *
     * <code>string iconTitle = 5;</code>
     * @return The bytes for iconTitle.
     */
    com.google.protobuf.ByteString
        getIconTitleBytes();

    /**
     * <pre>
     *图标类型。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The enum numeric value on the wire for iconType.
     */
    int getIconTypeValue();
    /**
     * <pre>
     *图标类型。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The iconType.
     */
    com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType();

    /**
     * <pre>
     *图片文件内容。
     * </pre>
     *
     * <code>bytes pictureFileContent = 7;</code>
     * @return The pictureFileContent.
     */
    com.google.protobuf.ByteString getPictureFileContent();
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage}
   */
  public  static final class VoiceCommandHitDataMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage)
      VoiceCommandHitDataMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoiceCommandHitDataMessage.newBuilder() to construct.
    private VoiceCommandHitDataMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoiceCommandHitDataMessage() {
      voiceRecognizeResult_ = "";
      packageName_ = "";
      asrWavFileContent_ = com.google.protobuf.ByteString.EMPTY;
      activityName_ = "";
      iconTitle_ = "";
      iconType_ = 0;
      pictureFileContent_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoiceCommandHitDataMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoiceCommandHitDataMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              voiceRecognizeResult_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              packageName_ = s;
              break;
            }
            case 26: {

              asrWavFileContent_ = input.readBytes();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              activityName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              iconTitle_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              iconType_ = rawValue;
              break;
            }
            case 58: {

              pictureFileContent_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.class, com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.Builder.class);
    }

    public static final int VOICERECOGNIZERESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object voiceRecognizeResult_;
    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The voiceRecognizeResult.
     */
    public java.lang.String getVoiceRecognizeResult() {
      java.lang.Object ref = voiceRecognizeResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voiceRecognizeResult_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The bytes for voiceRecognizeResult.
     */
    public com.google.protobuf.ByteString
        getVoiceRecognizeResultBytes() {
      java.lang.Object ref = voiceRecognizeResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voiceRecognizeResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object packageName_;
    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASRWAVFILECONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString asrWavFileContent_;
    /**
     * <pre>
     *录音文件内容。
     * </pre>
     *
     * <code>bytes asrWavFileContent = 3;</code>
     * @return The asrWavFileContent.
     */
    public com.google.protobuf.ByteString getAsrWavFileContent() {
      return asrWavFileContent_;
    }

    public static final int ACTIVITYNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object activityName_;
    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The activityName.
     */
    public java.lang.String getActivityName() {
      java.lang.Object ref = activityName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activityName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The bytes for activityName.
     */
    public com.google.protobuf.ByteString
        getActivityNameBytes() {
      java.lang.Object ref = activityName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICONTITLE_FIELD_NUMBER = 5;
    private volatile java.lang.Object iconTitle_;
    /**
     * <pre>
     *图标标题。
     * </pre>
     *
     * <code>string iconTitle = 5;</code>
     * @return The iconTitle.
     */
    public java.lang.String getIconTitle() {
      java.lang.Object ref = iconTitle_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconTitle_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *图标标题。
     * </pre>
     *
     * <code>string iconTitle = 5;</code>
     * @return The bytes for iconTitle.
     */
    public com.google.protobuf.ByteString
        getIconTitleBytes() {
      java.lang.Object ref = iconTitle_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICONTYPE_FIELD_NUMBER = 6;
    private int iconType_;
    /**
     * <pre>
     *图标类型。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The enum numeric value on the wire for iconType.
     */
    public int getIconTypeValue() {
      return iconType_;
    }
    /**
     * <pre>
     *图标类型。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The iconType.
     */
    public com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType() {
      @SuppressWarnings("deprecation")
      com.stupidbeauty.hxlauncher.HxLauncherIconType result = com.stupidbeauty.hxlauncher.HxLauncherIconType.valueOf(iconType_);
      return result == null ? com.stupidbeauty.hxlauncher.HxLauncherIconType.UNRECOGNIZED : result;
    }

    public static final int PICTUREFILECONTENT_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString pictureFileContent_;
    /**
     * <pre>
     *图片文件内容。
     * </pre>
     *
     * <code>bytes pictureFileContent = 7;</code>
     * @return The pictureFileContent.
     */
    public com.google.protobuf.ByteString getPictureFileContent() {
      return pictureFileContent_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVoiceRecognizeResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, voiceRecognizeResult_);
      }
      if (!getPackageNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, packageName_);
      }
      if (!asrWavFileContent_.isEmpty()) {
        output.writeBytes(3, asrWavFileContent_);
      }
      if (!getActivityNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, activityName_);
      }
      if (!getIconTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, iconTitle_);
      }
      if (iconType_ != com.stupidbeauty.hxlauncher.HxLauncherIconType.NonsenseIconType.getNumber()) {
        output.writeEnum(6, iconType_);
      }
      if (!pictureFileContent_.isEmpty()) {
        output.writeBytes(7, pictureFileContent_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVoiceRecognizeResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, voiceRecognizeResult_);
      }
      if (!getPackageNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, packageName_);
      }
      if (!asrWavFileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, asrWavFileContent_);
      }
      if (!getActivityNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, activityName_);
      }
      if (!getIconTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, iconTitle_);
      }
      if (iconType_ != com.stupidbeauty.hxlauncher.HxLauncherIconType.NonsenseIconType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, iconType_);
      }
      if (!pictureFileContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, pictureFileContent_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage other = (com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage) obj;

      if (!getVoiceRecognizeResult()
          .equals(other.getVoiceRecognizeResult())) return false;
      if (!getPackageName()
          .equals(other.getPackageName())) return false;
      if (!getAsrWavFileContent()
          .equals(other.getAsrWavFileContent())) return false;
      if (!getActivityName()
          .equals(other.getActivityName())) return false;
      if (!getIconTitle()
          .equals(other.getIconTitle())) return false;
      if (iconType_ != other.iconType_) return false;
      if (!getPictureFileContent()
          .equals(other.getPictureFileContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOICERECOGNIZERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getVoiceRecognizeResult().hashCode();
      hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getPackageName().hashCode();
      hash = (37 * hash) + ASRWAVFILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getAsrWavFileContent().hashCode();
      hash = (37 * hash) + ACTIVITYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getActivityName().hashCode();
      hash = (37 * hash) + ICONTITLE_FIELD_NUMBER;
      hash = (53 * hash) + getIconTitle().hashCode();
      hash = (37 * hash) + ICONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + iconType_;
      hash = (37 * hash) + PICTUREFILECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getPictureFileContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage)
        com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.class, com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voiceRecognizeResult_ = "";

        packageName_ = "";

        asrWavFileContent_ = com.google.protobuf.ByteString.EMPTY;

        activityName_ = "";

        iconTitle_ = "";

        iconType_ = 0;

        pictureFileContent_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage build() {
        com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage buildPartial() {
        com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage result = new com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage(this);
        result.voiceRecognizeResult_ = voiceRecognizeResult_;
        result.packageName_ = packageName_;
        result.asrWavFileContent_ = asrWavFileContent_;
        result.activityName_ = activityName_;
        result.iconTitle_ = iconTitle_;
        result.iconType_ = iconType_;
        result.pictureFileContent_ = pictureFileContent_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage) {
          return mergeFrom((com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage other) {
        if (other == com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage.getDefaultInstance()) return this;
        if (!other.getVoiceRecognizeResult().isEmpty()) {
          voiceRecognizeResult_ = other.voiceRecognizeResult_;
          onChanged();
        }
        if (!other.getPackageName().isEmpty()) {
          packageName_ = other.packageName_;
          onChanged();
        }
        if (other.getAsrWavFileContent() != com.google.protobuf.ByteString.EMPTY) {
          setAsrWavFileContent(other.getAsrWavFileContent());
        }
        if (!other.getActivityName().isEmpty()) {
          activityName_ = other.activityName_;
          onChanged();
        }
        if (!other.getIconTitle().isEmpty()) {
          iconTitle_ = other.iconTitle_;
          onChanged();
        }
        if (other.iconType_ != 0) {
          setIconTypeValue(other.getIconTypeValue());
        }
        if (other.getPictureFileContent() != com.google.protobuf.ByteString.EMPTY) {
          setPictureFileContent(other.getPictureFileContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object voiceRecognizeResult_ = "";
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @return The voiceRecognizeResult.
       */
      public java.lang.String getVoiceRecognizeResult() {
        java.lang.Object ref = voiceRecognizeResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          voiceRecognizeResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @return The bytes for voiceRecognizeResult.
       */
      public com.google.protobuf.ByteString
          getVoiceRecognizeResultBytes() {
        java.lang.Object ref = voiceRecognizeResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          voiceRecognizeResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @param value The voiceRecognizeResult to set.
       * @return This builder for chaining.
       */
      public Builder setVoiceRecognizeResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        voiceRecognizeResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoiceRecognizeResult() {
        
        voiceRecognizeResult_ = getDefaultInstance().getVoiceRecognizeResult();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @param value The bytes for voiceRecognizeResult to set.
       * @return This builder for chaining.
       */
      public Builder setVoiceRecognizeResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        voiceRecognizeResult_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object packageName_ = "";
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @return The packageName.
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          packageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @return The bytes for packageName.
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @param value The packageName to set.
       * @return This builder for chaining.
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageName() {
        
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @param value The bytes for packageName to set.
       * @return This builder for chaining.
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        packageName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString asrWavFileContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *录音文件内容。
       * </pre>
       *
       * <code>bytes asrWavFileContent = 3;</code>
       * @return The asrWavFileContent.
       */
      public com.google.protobuf.ByteString getAsrWavFileContent() {
        return asrWavFileContent_;
      }
      /**
       * <pre>
       *录音文件内容。
       * </pre>
       *
       * <code>bytes asrWavFileContent = 3;</code>
       * @param value The asrWavFileContent to set.
       * @return This builder for chaining.
       */
      public Builder setAsrWavFileContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        asrWavFileContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *录音文件内容。
       * </pre>
       *
       * <code>bytes asrWavFileContent = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsrWavFileContent() {
        
        asrWavFileContent_ = getDefaultInstance().getAsrWavFileContent();
        onChanged();
        return this;
      }

      private java.lang.Object activityName_ = "";
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @return The activityName.
       */
      public java.lang.String getActivityName() {
        java.lang.Object ref = activityName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          activityName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @return The bytes for activityName.
       */
      public com.google.protobuf.ByteString
          getActivityNameBytes() {
        java.lang.Object ref = activityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          activityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @param value The activityName to set.
       * @return This builder for chaining.
       */
      public Builder setActivityName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        activityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearActivityName() {
        
        activityName_ = getDefaultInstance().getActivityName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @param value The bytes for activityName to set.
       * @return This builder for chaining.
       */
      public Builder setActivityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        activityName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iconTitle_ = "";
      /**
       * <pre>
       *图标标题。
       * </pre>
       *
       * <code>string iconTitle = 5;</code>
       * @return The iconTitle.
       */
      public java.lang.String getIconTitle() {
        java.lang.Object ref = iconTitle_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iconTitle_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *图标标题。
       * </pre>
       *
       * <code>string iconTitle = 5;</code>
       * @return The bytes for iconTitle.
       */
      public com.google.protobuf.ByteString
          getIconTitleBytes() {
        java.lang.Object ref = iconTitle_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconTitle_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *图标标题。
       * </pre>
       *
       * <code>string iconTitle = 5;</code>
       * @param value The iconTitle to set.
       * @return This builder for chaining.
       */
      public Builder setIconTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iconTitle_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图标标题。
       * </pre>
       *
       * <code>string iconTitle = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIconTitle() {
        
        iconTitle_ = getDefaultInstance().getIconTitle();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图标标题。
       * </pre>
       *
       * <code>string iconTitle = 5;</code>
       * @param value The bytes for iconTitle to set.
       * @return This builder for chaining.
       */
      public Builder setIconTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iconTitle_ = value;
        onChanged();
        return this;
      }

      private int iconType_ = 0;
      /**
       * <pre>
       *图标类型。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @return The enum numeric value on the wire for iconType.
       */
      public int getIconTypeValue() {
        return iconType_;
      }
      /**
       * <pre>
       *图标类型。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @param value The enum numeric value on the wire for iconType to set.
       * @return This builder for chaining.
       */
      public Builder setIconTypeValue(int value) {
        iconType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图标类型。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @return The iconType.
       */
      public com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType() {
        @SuppressWarnings("deprecation")
        com.stupidbeauty.hxlauncher.HxLauncherIconType result = com.stupidbeauty.hxlauncher.HxLauncherIconType.valueOf(iconType_);
        return result == null ? com.stupidbeauty.hxlauncher.HxLauncherIconType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *图标类型。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @param value The iconType to set.
       * @return This builder for chaining.
       */
      public Builder setIconType(com.stupidbeauty.hxlauncher.HxLauncherIconType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        iconType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图标类型。
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIconType() {
        
        iconType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pictureFileContent_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *图片文件内容。
       * </pre>
       *
       * <code>bytes pictureFileContent = 7;</code>
       * @return The pictureFileContent.
       */
      public com.google.protobuf.ByteString getPictureFileContent() {
        return pictureFileContent_;
      }
      /**
       * <pre>
       *图片文件内容。
       * </pre>
       *
       * <code>bytes pictureFileContent = 7;</code>
       * @param value The pictureFileContent to set.
       * @return This builder for chaining.
       */
      public Builder setPictureFileContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pictureFileContent_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图片文件内容。
       * </pre>
       *
       * <code>bytes pictureFileContent = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPictureFileContent() {
        
        pictureFileContent_ = getDefaultInstance().getPictureFileContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessage)
    private static final com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage();
    }

    public static com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoiceCommandHitDataMessage>
        PARSER = new com.google.protobuf.AbstractParser<VoiceCommandHitDataMessage>() {
      @java.lang.Override
      public VoiceCommandHitDataMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoiceCommandHitDataMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoiceCommandHitDataMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoiceCommandHitDataMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.VoiceCommandHitDataMessageProtos.VoiceCommandHitDataMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n VoiceCommandHitDataMessage.proto\022\033com." +
      "stupidbeauty.hxlauncher\032\030HxLauncherIconT" +
      "ype.proto\"\362\001\n\032VoiceCommandHitDataMessage" +
      "\022\034\n\024voiceRecognizeResult\030\001 \001(\t\022\023\n\013packag" +
      "eName\030\002 \001(\t\022\031\n\021asrWavFileContent\030\003 \001(\014\022\024" +
      "\n\014activityName\030\004 \001(\t\022\021\n\ticonTitle\030\005 \001(\t\022" +
      "A\n\010iconType\030\006 \001(\0162/.com.stupidbeauty.hxl" +
      "auncher.HxLauncherIconType\022\032\n\022pictureFil" +
      "eContent\030\007 \001(\014B?\n\033com.stupidbeauty.hxlau" +
      "ncherB VoiceCommandHitDataMessageProtosb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_VoiceCommandHitDataMessage_descriptor,
        new java.lang.String[] { "VoiceRecognizeResult", "PackageName", "AsrWavFileContent", "ActivityName", "IconTitle", "IconType", "PictureFileContent", });
    com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
