// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceCommandMessage.proto

package com.stupidbeauty.hxlauncher;

public final class VoiceCommandMessageProtos {
  private VoiceCommandMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_VoiceCommandMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_VoiceCommandMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031VoiceCommandMessage.proto\022\033com.stupidb" +
      "eauty.hxlauncher\032\037ReportAudioSoundSource" +
      "Req.proto\032*Set3DEngineCameraPositionRota" +
      "tionReq.proto\032\035AccurateVoiceCommandReq.p" +
      "roto\032\036ReportVoiceRecognizedReq.proto\032\"Re" +
      "portFaceRecognizeResultReq.proto\"\256\004\n\023Voi" +
      "ceCommandMessage\022\017\n\007command\030\001 \001(\t\022\014\n\004cod" +
      "e\030\002 \001(\005\022`\n reportAudioSoundSourceReqMess" +
      "age\030\006 \001(\01326.com.stupidbeauty.hxlauncher." +
      "ReportAudioSoundSourceReq\022s\n(set3DEngine" +
      "CameraPositionRotationMessage\030\010 \001(\0132A.co" +
      "m.stupidbeauty.hxlauncher.Set3DEngineCam" +
      "eraPositionRotationReq\022_\n!reportAccurate" +
      "VoiceCommandMessage\030\023 \001(\01324.com.stupidbe" +
      "auty.hxlauncher.AccurateVoiceCommandReq\022" +
      "[\n\034reportVoiceRecognizedMessage\030\024 \001(\01325." +
      "com.stupidbeauty.hxlauncher.ReportVoiceR" +
      "ecognizedReq\022c\n reportFaceRecognizeResul" +
      "tMessage\030\027 \001(\01329.com.stupidbeauty.hxlaun" +
      "cher.ReportFaceRecognizeResultReqB:\n\033com" +
      ".stupidbeauty.hxlauncherB\031VoiceCommandMe" +
      "ssageProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_VoiceCommandMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_VoiceCommandMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_VoiceCommandMessage_descriptor,
        new java.lang.String[] { "Command", "Code", "ReportAudioSoundSourceReqMessage", "Set3DEngineCameraPositionRotationMessage", "ReportAccurateVoiceCommandMessage", "ReportVoiceRecognizedMessage", "ReportFaceRecognizeResultMessage", });
    com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
