// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoicePackageMapItemMessage.proto

package com.stupidbeauty.hxlauncher;

public final class VoicePackageMapItemMessageProtos {
  private VoicePackageMapItemMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VoicePackageMapItemMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The voiceRecognizeResult.
     */
    java.lang.String getVoiceRecognizeResult();
    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The bytes for voiceRecognizeResult.
     */
    com.google.protobuf.ByteString
        getVoiceRecognizeResultBytes();

    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The packageName.
     */
    java.lang.String getPackageName();
    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The bytes for packageName.
     */
    com.google.protobuf.ByteString
        getPackageNameBytes();

    /**
     * <pre>
     *安装包的下载地址。
     * </pre>
     *
     * <code>string packageUrl = 3;</code>
     * @return The packageUrl.
     */
    java.lang.String getPackageUrl();
    /**
     * <pre>
     *安装包的下载地址。
     * </pre>
     *
     * <code>string packageUrl = 3;</code>
     * @return The bytes for packageUrl.
     */
    com.google.protobuf.ByteString
        getPackageUrlBytes();

    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The activityName.
     */
    java.lang.String getActivityName();
    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The bytes for activityName.
     */
    com.google.protobuf.ByteString
        getActivityNameBytes();

    /**
     * <pre>
     *!&lt;快捷方式编号．
     * </pre>
     *
     * <code>string shortcutId = 5;</code>
     * @return The shortcutId.
     */
    java.lang.String getShortcutId();
    /**
     * <pre>
     *!&lt;快捷方式编号．
     * </pre>
     *
     * <code>string shortcutId = 5;</code>
     * @return The bytes for shortcutId.
     */
    com.google.protobuf.ByteString
        getShortcutIdBytes();

    /**
     * <pre>
     *!&lt;图标类型．
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The enum numeric value on the wire for iconType.
     */
    int getIconTypeValue();
    /**
     * <pre>
     *!&lt;图标类型．
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The iconType.
     */
    com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType();

    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage> 
        getApplicationInformationList();
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    com.stupidbeauty.hxlauncher.AndroidApplicationMessage getApplicationInformation(int index);
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    int getApplicationInformationCount();
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    java.util.List<? extends com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder> 
        getApplicationInformationOrBuilderList();
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder getApplicationInformationOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage}
   */
  public  static final class VoicePackageMapItemMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage)
      VoicePackageMapItemMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoicePackageMapItemMessage.newBuilder() to construct.
    private VoicePackageMapItemMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoicePackageMapItemMessage() {
      voiceRecognizeResult_ = "";
      packageName_ = "";
      packageUrl_ = "";
      activityName_ = "";
      shortcutId_ = "";
      iconType_ = 0;
      applicationInformation_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoicePackageMapItemMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoicePackageMapItemMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              voiceRecognizeResult_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              packageName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              packageUrl_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              activityName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              shortcutId_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              iconType_ = rawValue;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                applicationInformation_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.AndroidApplicationMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              applicationInformation_.add(
                  input.readMessage(com.stupidbeauty.hxlauncher.AndroidApplicationMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          applicationInformation_ = java.util.Collections.unmodifiableList(applicationInformation_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.class, com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.Builder.class);
    }

    public static final int VOICERECOGNIZERESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object voiceRecognizeResult_;
    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The voiceRecognizeResult.
     */
    public java.lang.String getVoiceRecognizeResult() {
      java.lang.Object ref = voiceRecognizeResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voiceRecognizeResult_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *语音识别结果。
     * </pre>
     *
     * <code>string voiceRecognizeResult = 1;</code>
     * @return The bytes for voiceRecognizeResult.
     */
    public com.google.protobuf.ByteString
        getVoiceRecognizeResultBytes() {
      java.lang.Object ref = voiceRecognizeResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voiceRecognizeResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGENAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object packageName_;
    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The packageName.
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *对应的包名。
     * </pre>
     *
     * <code>string packageName = 2;</code>
     * @return The bytes for packageName.
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGEURL_FIELD_NUMBER = 3;
    private volatile java.lang.Object packageUrl_;
    /**
     * <pre>
     *安装包的下载地址。
     * </pre>
     *
     * <code>string packageUrl = 3;</code>
     * @return The packageUrl.
     */
    public java.lang.String getPackageUrl() {
      java.lang.Object ref = packageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageUrl_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *安装包的下载地址。
     * </pre>
     *
     * <code>string packageUrl = 3;</code>
     * @return The bytes for packageUrl.
     */
    public com.google.protobuf.ByteString
        getPackageUrlBytes() {
      java.lang.Object ref = packageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIVITYNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object activityName_;
    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The activityName.
     */
    public java.lang.String getActivityName() {
      java.lang.Object ref = activityName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activityName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *活动名字。
     * </pre>
     *
     * <code>string activityName = 4;</code>
     * @return The bytes for activityName.
     */
    public com.google.protobuf.ByteString
        getActivityNameBytes() {
      java.lang.Object ref = activityName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORTCUTID_FIELD_NUMBER = 5;
    private volatile java.lang.Object shortcutId_;
    /**
     * <pre>
     *!&lt;快捷方式编号．
     * </pre>
     *
     * <code>string shortcutId = 5;</code>
     * @return The shortcutId.
     */
    public java.lang.String getShortcutId() {
      java.lang.Object ref = shortcutId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortcutId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *!&lt;快捷方式编号．
     * </pre>
     *
     * <code>string shortcutId = 5;</code>
     * @return The bytes for shortcutId.
     */
    public com.google.protobuf.ByteString
        getShortcutIdBytes() {
      java.lang.Object ref = shortcutId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortcutId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICONTYPE_FIELD_NUMBER = 6;
    private int iconType_;
    /**
     * <pre>
     *!&lt;图标类型．
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The enum numeric value on the wire for iconType.
     */
    public int getIconTypeValue() {
      return iconType_;
    }
    /**
     * <pre>
     *!&lt;图标类型．
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
     * @return The iconType.
     */
    public com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType() {
      @SuppressWarnings("deprecation")
      com.stupidbeauty.hxlauncher.HxLauncherIconType result = com.stupidbeauty.hxlauncher.HxLauncherIconType.valueOf(iconType_);
      return result == null ? com.stupidbeauty.hxlauncher.HxLauncherIconType.UNRECOGNIZED : result;
    }

    public static final int APPLICATIONINFORMATION_FIELD_NUMBER = 7;
    private java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage> applicationInformation_;
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    public java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage> getApplicationInformationList() {
      return applicationInformation_;
    }
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    public java.util.List<? extends com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder> 
        getApplicationInformationOrBuilderList() {
      return applicationInformation_;
    }
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    public int getApplicationInformationCount() {
      return applicationInformation_.size();
    }
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    public com.stupidbeauty.hxlauncher.AndroidApplicationMessage getApplicationInformation(int index) {
      return applicationInformation_.get(index);
    }
    /**
     * <pre>
     *!&lt;命中的应用程序信息。替代2、3、4、5、6
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
     */
    public com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder getApplicationInformationOrBuilder(
        int index) {
      return applicationInformation_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVoiceRecognizeResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, voiceRecognizeResult_);
      }
      if (!getPackageNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, packageName_);
      }
      if (!getPackageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, packageUrl_);
      }
      if (!getActivityNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, activityName_);
      }
      if (!getShortcutIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, shortcutId_);
      }
      if (iconType_ != com.stupidbeauty.hxlauncher.HxLauncherIconType.NonsenseIconType.getNumber()) {
        output.writeEnum(6, iconType_);
      }
      for (int i = 0; i < applicationInformation_.size(); i++) {
        output.writeMessage(7, applicationInformation_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVoiceRecognizeResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, voiceRecognizeResult_);
      }
      if (!getPackageNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, packageName_);
      }
      if (!getPackageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, packageUrl_);
      }
      if (!getActivityNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, activityName_);
      }
      if (!getShortcutIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, shortcutId_);
      }
      if (iconType_ != com.stupidbeauty.hxlauncher.HxLauncherIconType.NonsenseIconType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, iconType_);
      }
      for (int i = 0; i < applicationInformation_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, applicationInformation_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage other = (com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage) obj;

      if (!getVoiceRecognizeResult()
          .equals(other.getVoiceRecognizeResult())) return false;
      if (!getPackageName()
          .equals(other.getPackageName())) return false;
      if (!getPackageUrl()
          .equals(other.getPackageUrl())) return false;
      if (!getActivityName()
          .equals(other.getActivityName())) return false;
      if (!getShortcutId()
          .equals(other.getShortcutId())) return false;
      if (iconType_ != other.iconType_) return false;
      if (!getApplicationInformationList()
          .equals(other.getApplicationInformationList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VOICERECOGNIZERESULT_FIELD_NUMBER;
      hash = (53 * hash) + getVoiceRecognizeResult().hashCode();
      hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
      hash = (53 * hash) + getPackageName().hashCode();
      hash = (37 * hash) + PACKAGEURL_FIELD_NUMBER;
      hash = (53 * hash) + getPackageUrl().hashCode();
      hash = (37 * hash) + ACTIVITYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getActivityName().hashCode();
      hash = (37 * hash) + SHORTCUTID_FIELD_NUMBER;
      hash = (53 * hash) + getShortcutId().hashCode();
      hash = (37 * hash) + ICONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + iconType_;
      if (getApplicationInformationCount() > 0) {
        hash = (37 * hash) + APPLICATIONINFORMATION_FIELD_NUMBER;
        hash = (53 * hash) + getApplicationInformationList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage)
        com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.class, com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getApplicationInformationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        voiceRecognizeResult_ = "";

        packageName_ = "";

        packageUrl_ = "";

        activityName_ = "";

        shortcutId_ = "";

        iconType_ = 0;

        if (applicationInformationBuilder_ == null) {
          applicationInformation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          applicationInformationBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage build() {
        com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage buildPartial() {
        com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage result = new com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage(this);
        int from_bitField0_ = bitField0_;
        result.voiceRecognizeResult_ = voiceRecognizeResult_;
        result.packageName_ = packageName_;
        result.packageUrl_ = packageUrl_;
        result.activityName_ = activityName_;
        result.shortcutId_ = shortcutId_;
        result.iconType_ = iconType_;
        if (applicationInformationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            applicationInformation_ = java.util.Collections.unmodifiableList(applicationInformation_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.applicationInformation_ = applicationInformation_;
        } else {
          result.applicationInformation_ = applicationInformationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage) {
          return mergeFrom((com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage other) {
        if (other == com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage.getDefaultInstance()) return this;
        if (!other.getVoiceRecognizeResult().isEmpty()) {
          voiceRecognizeResult_ = other.voiceRecognizeResult_;
          onChanged();
        }
        if (!other.getPackageName().isEmpty()) {
          packageName_ = other.packageName_;
          onChanged();
        }
        if (!other.getPackageUrl().isEmpty()) {
          packageUrl_ = other.packageUrl_;
          onChanged();
        }
        if (!other.getActivityName().isEmpty()) {
          activityName_ = other.activityName_;
          onChanged();
        }
        if (!other.getShortcutId().isEmpty()) {
          shortcutId_ = other.shortcutId_;
          onChanged();
        }
        if (other.iconType_ != 0) {
          setIconTypeValue(other.getIconTypeValue());
        }
        if (applicationInformationBuilder_ == null) {
          if (!other.applicationInformation_.isEmpty()) {
            if (applicationInformation_.isEmpty()) {
              applicationInformation_ = other.applicationInformation_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureApplicationInformationIsMutable();
              applicationInformation_.addAll(other.applicationInformation_);
            }
            onChanged();
          }
        } else {
          if (!other.applicationInformation_.isEmpty()) {
            if (applicationInformationBuilder_.isEmpty()) {
              applicationInformationBuilder_.dispose();
              applicationInformationBuilder_ = null;
              applicationInformation_ = other.applicationInformation_;
              bitField0_ = (bitField0_ & ~0x00000001);
              applicationInformationBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getApplicationInformationFieldBuilder() : null;
            } else {
              applicationInformationBuilder_.addAllMessages(other.applicationInformation_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object voiceRecognizeResult_ = "";
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @return The voiceRecognizeResult.
       */
      public java.lang.String getVoiceRecognizeResult() {
        java.lang.Object ref = voiceRecognizeResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          voiceRecognizeResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @return The bytes for voiceRecognizeResult.
       */
      public com.google.protobuf.ByteString
          getVoiceRecognizeResultBytes() {
        java.lang.Object ref = voiceRecognizeResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          voiceRecognizeResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @param value The voiceRecognizeResult to set.
       * @return This builder for chaining.
       */
      public Builder setVoiceRecognizeResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        voiceRecognizeResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoiceRecognizeResult() {
        
        voiceRecognizeResult_ = getDefaultInstance().getVoiceRecognizeResult();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *语音识别结果。
       * </pre>
       *
       * <code>string voiceRecognizeResult = 1;</code>
       * @param value The bytes for voiceRecognizeResult to set.
       * @return This builder for chaining.
       */
      public Builder setVoiceRecognizeResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        voiceRecognizeResult_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object packageName_ = "";
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @return The packageName.
       */
      public java.lang.String getPackageName() {
        java.lang.Object ref = packageName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          packageName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @return The bytes for packageName.
       */
      public com.google.protobuf.ByteString
          getPackageNameBytes() {
        java.lang.Object ref = packageName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @param value The packageName to set.
       * @return This builder for chaining.
       */
      public Builder setPackageName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        packageName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageName() {
        
        packageName_ = getDefaultInstance().getPackageName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *对应的包名。
       * </pre>
       *
       * <code>string packageName = 2;</code>
       * @param value The bytes for packageName to set.
       * @return This builder for chaining.
       */
      public Builder setPackageNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        packageName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object packageUrl_ = "";
      /**
       * <pre>
       *安装包的下载地址。
       * </pre>
       *
       * <code>string packageUrl = 3;</code>
       * @return The packageUrl.
       */
      public java.lang.String getPackageUrl() {
        java.lang.Object ref = packageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          packageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *安装包的下载地址。
       * </pre>
       *
       * <code>string packageUrl = 3;</code>
       * @return The bytes for packageUrl.
       */
      public com.google.protobuf.ByteString
          getPackageUrlBytes() {
        java.lang.Object ref = packageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *安装包的下载地址。
       * </pre>
       *
       * <code>string packageUrl = 3;</code>
       * @param value The packageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPackageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        packageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安装包的下载地址。
       * </pre>
       *
       * <code>string packageUrl = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageUrl() {
        
        packageUrl_ = getDefaultInstance().getPackageUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *安装包的下载地址。
       * </pre>
       *
       * <code>string packageUrl = 3;</code>
       * @param value The bytes for packageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPackageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        packageUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object activityName_ = "";
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @return The activityName.
       */
      public java.lang.String getActivityName() {
        java.lang.Object ref = activityName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          activityName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @return The bytes for activityName.
       */
      public com.google.protobuf.ByteString
          getActivityNameBytes() {
        java.lang.Object ref = activityName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          activityName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @param value The activityName to set.
       * @return This builder for chaining.
       */
      public Builder setActivityName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        activityName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearActivityName() {
        
        activityName_ = getDefaultInstance().getActivityName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *活动名字。
       * </pre>
       *
       * <code>string activityName = 4;</code>
       * @param value The bytes for activityName to set.
       * @return This builder for chaining.
       */
      public Builder setActivityNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        activityName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shortcutId_ = "";
      /**
       * <pre>
       *!&lt;快捷方式编号．
       * </pre>
       *
       * <code>string shortcutId = 5;</code>
       * @return The shortcutId.
       */
      public java.lang.String getShortcutId() {
        java.lang.Object ref = shortcutId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shortcutId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *!&lt;快捷方式编号．
       * </pre>
       *
       * <code>string shortcutId = 5;</code>
       * @return The bytes for shortcutId.
       */
      public com.google.protobuf.ByteString
          getShortcutIdBytes() {
        java.lang.Object ref = shortcutId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortcutId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *!&lt;快捷方式编号．
       * </pre>
       *
       * <code>string shortcutId = 5;</code>
       * @param value The shortcutId to set.
       * @return This builder for chaining.
       */
      public Builder setShortcutId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortcutId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;快捷方式编号．
       * </pre>
       *
       * <code>string shortcutId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearShortcutId() {
        
        shortcutId_ = getDefaultInstance().getShortcutId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;快捷方式编号．
       * </pre>
       *
       * <code>string shortcutId = 5;</code>
       * @param value The bytes for shortcutId to set.
       * @return This builder for chaining.
       */
      public Builder setShortcutIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shortcutId_ = value;
        onChanged();
        return this;
      }

      private int iconType_ = 0;
      /**
       * <pre>
       *!&lt;图标类型．
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @return The enum numeric value on the wire for iconType.
       */
      public int getIconTypeValue() {
        return iconType_;
      }
      /**
       * <pre>
       *!&lt;图标类型．
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @param value The enum numeric value on the wire for iconType to set.
       * @return This builder for chaining.
       */
      public Builder setIconTypeValue(int value) {
        iconType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;图标类型．
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @return The iconType.
       */
      public com.stupidbeauty.hxlauncher.HxLauncherIconType getIconType() {
        @SuppressWarnings("deprecation")
        com.stupidbeauty.hxlauncher.HxLauncherIconType result = com.stupidbeauty.hxlauncher.HxLauncherIconType.valueOf(iconType_);
        return result == null ? com.stupidbeauty.hxlauncher.HxLauncherIconType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *!&lt;图标类型．
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @param value The iconType to set.
       * @return This builder for chaining.
       */
      public Builder setIconType(com.stupidbeauty.hxlauncher.HxLauncherIconType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        iconType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *!&lt;图标类型．
       * </pre>
       *
       * <code>.com.stupidbeauty.hxlauncher.HxLauncherIconType iconType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIconType() {
        
        iconType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage> applicationInformation_ =
        java.util.Collections.emptyList();
      private void ensureApplicationInformationIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          applicationInformation_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.AndroidApplicationMessage>(applicationInformation_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.AndroidApplicationMessage, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder, com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder> applicationInformationBuilder_;

      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage> getApplicationInformationList() {
        if (applicationInformationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(applicationInformation_);
        } else {
          return applicationInformationBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public int getApplicationInformationCount() {
        if (applicationInformationBuilder_ == null) {
          return applicationInformation_.size();
        } else {
          return applicationInformationBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public com.stupidbeauty.hxlauncher.AndroidApplicationMessage getApplicationInformation(int index) {
        if (applicationInformationBuilder_ == null) {
          return applicationInformation_.get(index);
        } else {
          return applicationInformationBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder setApplicationInformation(
          int index, com.stupidbeauty.hxlauncher.AndroidApplicationMessage value) {
        if (applicationInformationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureApplicationInformationIsMutable();
          applicationInformation_.set(index, value);
          onChanged();
        } else {
          applicationInformationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder setApplicationInformation(
          int index, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder builderForValue) {
        if (applicationInformationBuilder_ == null) {
          ensureApplicationInformationIsMutable();
          applicationInformation_.set(index, builderForValue.build());
          onChanged();
        } else {
          applicationInformationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder addApplicationInformation(com.stupidbeauty.hxlauncher.AndroidApplicationMessage value) {
        if (applicationInformationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureApplicationInformationIsMutable();
          applicationInformation_.add(value);
          onChanged();
        } else {
          applicationInformationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder addApplicationInformation(
          int index, com.stupidbeauty.hxlauncher.AndroidApplicationMessage value) {
        if (applicationInformationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureApplicationInformationIsMutable();
          applicationInformation_.add(index, value);
          onChanged();
        } else {
          applicationInformationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder addApplicationInformation(
          com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder builderForValue) {
        if (applicationInformationBuilder_ == null) {
          ensureApplicationInformationIsMutable();
          applicationInformation_.add(builderForValue.build());
          onChanged();
        } else {
          applicationInformationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder addApplicationInformation(
          int index, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder builderForValue) {
        if (applicationInformationBuilder_ == null) {
          ensureApplicationInformationIsMutable();
          applicationInformation_.add(index, builderForValue.build());
          onChanged();
        } else {
          applicationInformationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder addAllApplicationInformation(
          java.lang.Iterable<? extends com.stupidbeauty.hxlauncher.AndroidApplicationMessage> values) {
        if (applicationInformationBuilder_ == null) {
          ensureApplicationInformationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, applicationInformation_);
          onChanged();
        } else {
          applicationInformationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder clearApplicationInformation() {
        if (applicationInformationBuilder_ == null) {
          applicationInformation_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          applicationInformationBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public Builder removeApplicationInformation(int index) {
        if (applicationInformationBuilder_ == null) {
          ensureApplicationInformationIsMutable();
          applicationInformation_.remove(index);
          onChanged();
        } else {
          applicationInformationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder getApplicationInformationBuilder(
          int index) {
        return getApplicationInformationFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder getApplicationInformationOrBuilder(
          int index) {
        if (applicationInformationBuilder_ == null) {
          return applicationInformation_.get(index);  } else {
          return applicationInformationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public java.util.List<? extends com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder> 
           getApplicationInformationOrBuilderList() {
        if (applicationInformationBuilder_ != null) {
          return applicationInformationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(applicationInformation_);
        }
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder addApplicationInformationBuilder() {
        return getApplicationInformationFieldBuilder().addBuilder(
            com.stupidbeauty.hxlauncher.AndroidApplicationMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder addApplicationInformationBuilder(
          int index) {
        return getApplicationInformationFieldBuilder().addBuilder(
            index, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *!&lt;命中的应用程序信息。替代2、3、4、5、6
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.AndroidApplicationMessage applicationInformation = 7;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder> 
           getApplicationInformationBuilderList() {
        return getApplicationInformationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.AndroidApplicationMessage, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder, com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder> 
          getApplicationInformationFieldBuilder() {
        if (applicationInformationBuilder_ == null) {
          applicationInformationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.stupidbeauty.hxlauncher.AndroidApplicationMessage, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder, com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder>(
                  applicationInformation_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          applicationInformation_ = null;
        }
        return applicationInformationBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.VoicePackageMapItemMessage)
    private static final com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage();
    }

    public static com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoicePackageMapItemMessage>
        PARSER = new com.google.protobuf.AbstractParser<VoicePackageMapItemMessage>() {
      @java.lang.Override
      public VoicePackageMapItemMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoicePackageMapItemMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoicePackageMapItemMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoicePackageMapItemMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.VoicePackageMapItemMessageProtos.VoicePackageMapItemMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n VoicePackageMapItemMessage.proto\022\033com." +
      "stupidbeauty.hxlauncher\032\030HxLauncherIconT" +
      "ype.proto\032\037AndroidApplicationMessage.pro" +
      "to\"\250\002\n\032VoicePackageMapItemMessage\022\034\n\024voi" +
      "ceRecognizeResult\030\001 \001(\t\022\023\n\013packageName\030\002" +
      " \001(\t\022\022\n\npackageUrl\030\003 \001(\t\022\024\n\014activityName" +
      "\030\004 \001(\t\022\022\n\nshortcutId\030\005 \001(\t\022A\n\010iconType\030\006" +
      " \001(\0162/.com.stupidbeauty.hxlauncher.HxLau" +
      "ncherIconType\022V\n\026applicationInformation\030" +
      "\007 \003(\01326.com.stupidbeauty.hxlauncher.Andr" +
      "oidApplicationMessageB?\n\033com.stupidbeaut" +
      "y.hxlauncherB VoicePackageMapItemMessage" +
      "Protosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.getDescriptor(),
        });
    internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_VoicePackageMapItemMessage_descriptor,
        new java.lang.String[] { "VoiceRecognizeResult", "PackageName", "PackageUrl", "ActivityName", "ShortcutId", "IconType", "ApplicationInformation", });
    com.stupidbeauty.hxlauncher.HxLauncherIconTypeProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
