// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VoiceCommandMessage.proto

package com.stupidbeauty.hxlauncher;

public interface VoiceCommandMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.VoiceCommandMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *指令内容。
   * </pre>
   *
   * <code>string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <pre>
   *指令内容。
   * </pre>
   *
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <pre>
   *指令代码。
   * </pre>
   *
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return Whether the reportAudioSoundSourceReqMessage field is set.
   */
  boolean hasReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   * @return The reportAudioSoundSourceReqMessage.
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder();

  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   * @return Whether the set3DEngineCameraPositionRotationMessage field is set.
   */
  boolean hasSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   * @return The set3DEngineCameraPositionRotationMessage.
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq getSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder getSet3DEngineCameraPositionRotationMessageOrBuilder();

  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return Whether the reportAccurateVoiceCommandMessage field is set.
   */
  boolean hasReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   * @return The reportAccurateVoiceCommandMessage.
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq getReportAccurateVoiceCommandMessage();
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder getReportAccurateVoiceCommandMessageOrBuilder();

  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return Whether the reportVoiceRecognizedMessage field is set.
   */
  boolean hasReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   * @return The reportVoiceRecognizedMessage.
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage();
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder();

  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   * @return Whether the reportFaceRecognizeResultMessage field is set.
   */
  boolean hasReportFaceRecognizeResultMessage();
  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   * @return The reportFaceRecognizeResultMessage.
   */
  com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq getReportFaceRecognizeResultMessage();
  /**
   * <pre>
   *报告人脸识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq reportFaceRecognizeResultMessage = 23;</code>
   */
  com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReqOrBuilder getReportFaceRecognizeResultMessageOrBuilder();
}
